// Package graph hosts the GraphQL endpoint that fronts the ent client.
//
// The schema is generated by entgql (see internal/ent/entc.go); the
// resolver glue is generated by gqlgen (see gqlgen.yml). This package
// adds the resolver constructor and root server factory; everything
// else is generated.
package graph

import (
	"github.com/99designs/gqlgen/graphql"

	"github.com/nicolerenee/promptbook/internal/ent"
)

// Resolver is the root resolver. It carries the ent client every
// generated resolver method calls into.
type Resolver struct {
	client *ent.Client
}

// NewSchema builds an executable GraphQL schema rooted at the supplied
// ent client. The returned schema is wired into the gqlgen handler at
// the server-package layer.
func NewSchema(client *ent.Client) graphql.ExecutableSchema {
	return NewExecutableSchema(Config{
		Resolvers: &Resolver{client: client},
	})
}
