// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/nicolerenee/promptbook/internal/ent/castentry"
	"github.com/nicolerenee/promptbook/internal/ent/recording"
)

// CastEntry is the model entity for the CastEntry schema.
type CastEntry struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RecordingID holds the value of the "recording_id" field.
	RecordingID int64 `json:"recording_id,omitempty"`
	// PerformerID holds the value of the "performer_id" field.
	PerformerID int64 `json:"performer_id,omitempty"`
	// PerformerName holds the value of the "performer_name" field.
	PerformerName string `json:"performer_name,omitempty"`
	// PerformerSlug holds the value of the "performer_slug" field.
	PerformerSlug string `json:"performer_slug,omitempty"`
	// PerformerURL holds the value of the "performer_url" field.
	PerformerURL string `json:"performer_url,omitempty"`
	// CharacterID holds the value of the "character_id" field.
	CharacterID int64 `json:"character_id,omitempty"`
	// CharacterName holds the value of the "character_name" field.
	CharacterName string `json:"character_name,omitempty"`
	// CharacterSlug holds the value of the "character_slug" field.
	CharacterSlug string `json:"character_slug,omitempty"`
	// CharacterURL holds the value of the "character_url" field.
	CharacterURL string `json:"character_url,omitempty"`
	// CharacterOrder holds the value of the "character_order" field.
	CharacterOrder int `json:"character_order,omitempty"`
	// StatusLabel holds the value of the "status_label" field.
	StatusLabel *string `json:"status_label,omitempty"`
	// StatusAbbrev holds the value of the "status_abbrev" field.
	StatusAbbrev *string `json:"status_abbrev,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CastEntryQuery when eager-loading is set.
	Edges        CastEntryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CastEntryEdges holds the relations/edges for other nodes in the graph.
type CastEntryEdges struct {
	// Recording holds the value of the recording edge.
	Recording *Recording `json:"recording,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RecordingOrErr returns the Recording value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CastEntryEdges) RecordingOrErr() (*Recording, error) {
	if e.Recording != nil {
		return e.Recording, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: recording.Label}
	}
	return nil, &NotLoadedError{edge: "recording"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CastEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case castentry.FieldID, castentry.FieldRecordingID, castentry.FieldPerformerID, castentry.FieldCharacterID, castentry.FieldCharacterOrder:
			values[i] = new(sql.NullInt64)
		case castentry.FieldPerformerName, castentry.FieldPerformerSlug, castentry.FieldPerformerURL, castentry.FieldCharacterName, castentry.FieldCharacterSlug, castentry.FieldCharacterURL, castentry.FieldStatusLabel, castentry.FieldStatusAbbrev:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CastEntry fields.
func (_m *CastEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case castentry.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case castentry.FieldRecordingID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field recording_id", values[i])
			} else if value.Valid {
				_m.RecordingID = value.Int64
			}
		case castentry.FieldPerformerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field performer_id", values[i])
			} else if value.Valid {
				_m.PerformerID = value.Int64
			}
		case castentry.FieldPerformerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field performer_name", values[i])
			} else if value.Valid {
				_m.PerformerName = value.String
			}
		case castentry.FieldPerformerSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field performer_slug", values[i])
			} else if value.Valid {
				_m.PerformerSlug = value.String
			}
		case castentry.FieldPerformerURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field performer_url", values[i])
			} else if value.Valid {
				_m.PerformerURL = value.String
			}
		case castentry.FieldCharacterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field character_id", values[i])
			} else if value.Valid {
				_m.CharacterID = value.Int64
			}
		case castentry.FieldCharacterName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field character_name", values[i])
			} else if value.Valid {
				_m.CharacterName = value.String
			}
		case castentry.FieldCharacterSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field character_slug", values[i])
			} else if value.Valid {
				_m.CharacterSlug = value.String
			}
		case castentry.FieldCharacterURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field character_url", values[i])
			} else if value.Valid {
				_m.CharacterURL = value.String
			}
		case castentry.FieldCharacterOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field character_order", values[i])
			} else if value.Valid {
				_m.CharacterOrder = int(value.Int64)
			}
		case castentry.FieldStatusLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status_label", values[i])
			} else if value.Valid {
				_m.StatusLabel = new(string)
				*_m.StatusLabel = value.String
			}
		case castentry.FieldStatusAbbrev:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status_abbrev", values[i])
			} else if value.Valid {
				_m.StatusAbbrev = new(string)
				*_m.StatusAbbrev = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CastEntry.
// This includes values selected through modifiers, order, etc.
func (_m *CastEntry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRecording queries the "recording" edge of the CastEntry entity.
func (_m *CastEntry) QueryRecording() *RecordingQuery {
	return NewCastEntryClient(_m.config).QueryRecording(_m)
}

// Update returns a builder for updating this CastEntry.
// Note that you need to call CastEntry.Unwrap() before calling this method if this CastEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CastEntry) Update() *CastEntryUpdateOne {
	return NewCastEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CastEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CastEntry) Unwrap() *CastEntry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CastEntry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CastEntry) String() string {
	var builder strings.Builder
	builder.WriteString("CastEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("recording_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RecordingID))
	builder.WriteString(", ")
	builder.WriteString("performer_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PerformerID))
	builder.WriteString(", ")
	builder.WriteString("performer_name=")
	builder.WriteString(_m.PerformerName)
	builder.WriteString(", ")
	builder.WriteString("performer_slug=")
	builder.WriteString(_m.PerformerSlug)
	builder.WriteString(", ")
	builder.WriteString("performer_url=")
	builder.WriteString(_m.PerformerURL)
	builder.WriteString(", ")
	builder.WriteString("character_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CharacterID))
	builder.WriteString(", ")
	builder.WriteString("character_name=")
	builder.WriteString(_m.CharacterName)
	builder.WriteString(", ")
	builder.WriteString("character_slug=")
	builder.WriteString(_m.CharacterSlug)
	builder.WriteString(", ")
	builder.WriteString("character_url=")
	builder.WriteString(_m.CharacterURL)
	builder.WriteString(", ")
	builder.WriteString("character_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.CharacterOrder))
	builder.WriteString(", ")
	if v := _m.StatusLabel; v != nil {
		builder.WriteString("status_label=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.StatusAbbrev; v != nil {
		builder.WriteString("status_abbrev=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// CastEntries is a parsable slice of CastEntry.
type CastEntries []*CastEntry
