// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/nicolerenee/promptbook/internal/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/nicolerenee/promptbook/internal/ent/castentry"
	"github.com/nicolerenee/promptbook/internal/ent/character"
	"github.com/nicolerenee/promptbook/internal/ent/collectionentry"
	"github.com/nicolerenee/promptbook/internal/ent/historyevent"
	"github.com/nicolerenee/promptbook/internal/ent/jobrun"
	"github.com/nicolerenee/promptbook/internal/ent/jobstate"
	"github.com/nicolerenee/promptbook/internal/ent/manualimportqueue"
	"github.com/nicolerenee/promptbook/internal/ent/performer"
	"github.com/nicolerenee/promptbook/internal/ent/profile"
	"github.com/nicolerenee/promptbook/internal/ent/recording"
	"github.com/nicolerenee/promptbook/internal/ent/recordingimagechoice"
	"github.com/nicolerenee/promptbook/internal/ent/recordingversion"
	"github.com/nicolerenee/promptbook/internal/ent/show"
	"github.com/nicolerenee/promptbook/internal/ent/syncrun"
	"github.com/nicolerenee/promptbook/internal/ent/wantsentry"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// CastEntry is the client for interacting with the CastEntry builders.
	CastEntry *CastEntryClient
	// Character is the client for interacting with the Character builders.
	Character *CharacterClient
	// CollectionEntry is the client for interacting with the CollectionEntry builders.
	CollectionEntry *CollectionEntryClient
	// HistoryEvent is the client for interacting with the HistoryEvent builders.
	HistoryEvent *HistoryEventClient
	// JobRun is the client for interacting with the JobRun builders.
	JobRun *JobRunClient
	// JobState is the client for interacting with the JobState builders.
	JobState *JobStateClient
	// ManualImportQueue is the client for interacting with the ManualImportQueue builders.
	ManualImportQueue *ManualImportQueueClient
	// Performer is the client for interacting with the Performer builders.
	Performer *PerformerClient
	// Profile is the client for interacting with the Profile builders.
	Profile *ProfileClient
	// Recording is the client for interacting with the Recording builders.
	Recording *RecordingClient
	// RecordingImageChoice is the client for interacting with the RecordingImageChoice builders.
	RecordingImageChoice *RecordingImageChoiceClient
	// RecordingVersion is the client for interacting with the RecordingVersion builders.
	RecordingVersion *RecordingVersionClient
	// Show is the client for interacting with the Show builders.
	Show *ShowClient
	// SyncRun is the client for interacting with the SyncRun builders.
	SyncRun *SyncRunClient
	// WantsEntry is the client for interacting with the WantsEntry builders.
	WantsEntry *WantsEntryClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.CastEntry = NewCastEntryClient(c.config)
	c.Character = NewCharacterClient(c.config)
	c.CollectionEntry = NewCollectionEntryClient(c.config)
	c.HistoryEvent = NewHistoryEventClient(c.config)
	c.JobRun = NewJobRunClient(c.config)
	c.JobState = NewJobStateClient(c.config)
	c.ManualImportQueue = NewManualImportQueueClient(c.config)
	c.Performer = NewPerformerClient(c.config)
	c.Profile = NewProfileClient(c.config)
	c.Recording = NewRecordingClient(c.config)
	c.RecordingImageChoice = NewRecordingImageChoiceClient(c.config)
	c.RecordingVersion = NewRecordingVersionClient(c.config)
	c.Show = NewShowClient(c.config)
	c.SyncRun = NewSyncRunClient(c.config)
	c.WantsEntry = NewWantsEntryClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                  ctx,
		config:               cfg,
		CastEntry:            NewCastEntryClient(cfg),
		Character:            NewCharacterClient(cfg),
		CollectionEntry:      NewCollectionEntryClient(cfg),
		HistoryEvent:         NewHistoryEventClient(cfg),
		JobRun:               NewJobRunClient(cfg),
		JobState:             NewJobStateClient(cfg),
		ManualImportQueue:    NewManualImportQueueClient(cfg),
		Performer:            NewPerformerClient(cfg),
		Profile:              NewProfileClient(cfg),
		Recording:            NewRecordingClient(cfg),
		RecordingImageChoice: NewRecordingImageChoiceClient(cfg),
		RecordingVersion:     NewRecordingVersionClient(cfg),
		Show:                 NewShowClient(cfg),
		SyncRun:              NewSyncRunClient(cfg),
		WantsEntry:           NewWantsEntryClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                  ctx,
		config:               cfg,
		CastEntry:            NewCastEntryClient(cfg),
		Character:            NewCharacterClient(cfg),
		CollectionEntry:      NewCollectionEntryClient(cfg),
		HistoryEvent:         NewHistoryEventClient(cfg),
		JobRun:               NewJobRunClient(cfg),
		JobState:             NewJobStateClient(cfg),
		ManualImportQueue:    NewManualImportQueueClient(cfg),
		Performer:            NewPerformerClient(cfg),
		Profile:              NewProfileClient(cfg),
		Recording:            NewRecordingClient(cfg),
		RecordingImageChoice: NewRecordingImageChoiceClient(cfg),
		RecordingVersion:     NewRecordingVersionClient(cfg),
		Show:                 NewShowClient(cfg),
		SyncRun:              NewSyncRunClient(cfg),
		WantsEntry:           NewWantsEntryClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		CastEntry.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.CastEntry, c.Character, c.CollectionEntry, c.HistoryEvent, c.JobRun,
		c.JobState, c.ManualImportQueue, c.Performer, c.Profile, c.Recording,
		c.RecordingImageChoice, c.RecordingVersion, c.Show, c.SyncRun, c.WantsEntry,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.CastEntry, c.Character, c.CollectionEntry, c.HistoryEvent, c.JobRun,
		c.JobState, c.ManualImportQueue, c.Performer, c.Profile, c.Recording,
		c.RecordingImageChoice, c.RecordingVersion, c.Show, c.SyncRun, c.WantsEntry,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CastEntryMutation:
		return c.CastEntry.mutate(ctx, m)
	case *CharacterMutation:
		return c.Character.mutate(ctx, m)
	case *CollectionEntryMutation:
		return c.CollectionEntry.mutate(ctx, m)
	case *HistoryEventMutation:
		return c.HistoryEvent.mutate(ctx, m)
	case *JobRunMutation:
		return c.JobRun.mutate(ctx, m)
	case *JobStateMutation:
		return c.JobState.mutate(ctx, m)
	case *ManualImportQueueMutation:
		return c.ManualImportQueue.mutate(ctx, m)
	case *PerformerMutation:
		return c.Performer.mutate(ctx, m)
	case *ProfileMutation:
		return c.Profile.mutate(ctx, m)
	case *RecordingMutation:
		return c.Recording.mutate(ctx, m)
	case *RecordingImageChoiceMutation:
		return c.RecordingImageChoice.mutate(ctx, m)
	case *RecordingVersionMutation:
		return c.RecordingVersion.mutate(ctx, m)
	case *ShowMutation:
		return c.Show.mutate(ctx, m)
	case *SyncRunMutation:
		return c.SyncRun.mutate(ctx, m)
	case *WantsEntryMutation:
		return c.WantsEntry.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CastEntryClient is a client for the CastEntry schema.
type CastEntryClient struct {
	config
}

// NewCastEntryClient returns a client for the CastEntry from the given config.
func NewCastEntryClient(c config) *CastEntryClient {
	return &CastEntryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `castentry.Hooks(f(g(h())))`.
func (c *CastEntryClient) Use(hooks ...Hook) {
	c.hooks.CastEntry = append(c.hooks.CastEntry, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `castentry.Intercept(f(g(h())))`.
func (c *CastEntryClient) Intercept(interceptors ...Interceptor) {
	c.inters.CastEntry = append(c.inters.CastEntry, interceptors...)
}

// Create returns a builder for creating a CastEntry entity.
func (c *CastEntryClient) Create() *CastEntryCreate {
	mutation := newCastEntryMutation(c.config, OpCreate)
	return &CastEntryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CastEntry entities.
func (c *CastEntryClient) CreateBulk(builders ...*CastEntryCreate) *CastEntryCreateBulk {
	return &CastEntryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CastEntryClient) MapCreateBulk(slice any, setFunc func(*CastEntryCreate, int)) *CastEntryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CastEntryCreateBulk{err: fmt.Errorf("calling to CastEntryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CastEntryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CastEntryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CastEntry.
func (c *CastEntryClient) Update() *CastEntryUpdate {
	mutation := newCastEntryMutation(c.config, OpUpdate)
	return &CastEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CastEntryClient) UpdateOne(_m *CastEntry) *CastEntryUpdateOne {
	mutation := newCastEntryMutation(c.config, OpUpdateOne, withCastEntry(_m))
	return &CastEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CastEntryClient) UpdateOneID(id int) *CastEntryUpdateOne {
	mutation := newCastEntryMutation(c.config, OpUpdateOne, withCastEntryID(id))
	return &CastEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CastEntry.
func (c *CastEntryClient) Delete() *CastEntryDelete {
	mutation := newCastEntryMutation(c.config, OpDelete)
	return &CastEntryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CastEntryClient) DeleteOne(_m *CastEntry) *CastEntryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CastEntryClient) DeleteOneID(id int) *CastEntryDeleteOne {
	builder := c.Delete().Where(castentry.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CastEntryDeleteOne{builder}
}

// Query returns a query builder for CastEntry.
func (c *CastEntryClient) Query() *CastEntryQuery {
	return &CastEntryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCastEntry},
		inters: c.Interceptors(),
	}
}

// Get returns a CastEntry entity by its id.
func (c *CastEntryClient) Get(ctx context.Context, id int) (*CastEntry, error) {
	return c.Query().Where(castentry.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CastEntryClient) GetX(ctx context.Context, id int) *CastEntry {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRecording queries the recording edge of a CastEntry.
func (c *CastEntryClient) QueryRecording(_m *CastEntry) *RecordingQuery {
	query := (&RecordingClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(castentry.Table, castentry.FieldID, id),
			sqlgraph.To(recording.Table, recording.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, castentry.RecordingTable, castentry.RecordingColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CastEntryClient) Hooks() []Hook {
	return c.hooks.CastEntry
}

// Interceptors returns the client interceptors.
func (c *CastEntryClient) Interceptors() []Interceptor {
	return c.inters.CastEntry
}

func (c *CastEntryClient) mutate(ctx context.Context, m *CastEntryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CastEntryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CastEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CastEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CastEntryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CastEntry mutation op: %q", m.Op())
	}
}

// CharacterClient is a client for the Character schema.
type CharacterClient struct {
	config
}

// NewCharacterClient returns a client for the Character from the given config.
func NewCharacterClient(c config) *CharacterClient {
	return &CharacterClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `character.Hooks(f(g(h())))`.
func (c *CharacterClient) Use(hooks ...Hook) {
	c.hooks.Character = append(c.hooks.Character, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `character.Intercept(f(g(h())))`.
func (c *CharacterClient) Intercept(interceptors ...Interceptor) {
	c.inters.Character = append(c.inters.Character, interceptors...)
}

// Create returns a builder for creating a Character entity.
func (c *CharacterClient) Create() *CharacterCreate {
	mutation := newCharacterMutation(c.config, OpCreate)
	return &CharacterCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Character entities.
func (c *CharacterClient) CreateBulk(builders ...*CharacterCreate) *CharacterCreateBulk {
	return &CharacterCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CharacterClient) MapCreateBulk(slice any, setFunc func(*CharacterCreate, int)) *CharacterCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CharacterCreateBulk{err: fmt.Errorf("calling to CharacterClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CharacterCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CharacterCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Character.
func (c *CharacterClient) Update() *CharacterUpdate {
	mutation := newCharacterMutation(c.config, OpUpdate)
	return &CharacterUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CharacterClient) UpdateOne(_m *Character) *CharacterUpdateOne {
	mutation := newCharacterMutation(c.config, OpUpdateOne, withCharacter(_m))
	return &CharacterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CharacterClient) UpdateOneID(id int64) *CharacterUpdateOne {
	mutation := newCharacterMutation(c.config, OpUpdateOne, withCharacterID(id))
	return &CharacterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Character.
func (c *CharacterClient) Delete() *CharacterDelete {
	mutation := newCharacterMutation(c.config, OpDelete)
	return &CharacterDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CharacterClient) DeleteOne(_m *Character) *CharacterDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CharacterClient) DeleteOneID(id int64) *CharacterDeleteOne {
	builder := c.Delete().Where(character.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CharacterDeleteOne{builder}
}

// Query returns a query builder for Character.
func (c *CharacterClient) Query() *CharacterQuery {
	return &CharacterQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCharacter},
		inters: c.Interceptors(),
	}
}

// Get returns a Character entity by its id.
func (c *CharacterClient) Get(ctx context.Context, id int64) (*Character, error) {
	return c.Query().Where(character.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CharacterClient) GetX(ctx context.Context, id int64) *Character {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CharacterClient) Hooks() []Hook {
	return c.hooks.Character
}

// Interceptors returns the client interceptors.
func (c *CharacterClient) Interceptors() []Interceptor {
	return c.inters.Character
}

func (c *CharacterClient) mutate(ctx context.Context, m *CharacterMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CharacterCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CharacterUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CharacterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CharacterDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Character mutation op: %q", m.Op())
	}
}

// CollectionEntryClient is a client for the CollectionEntry schema.
type CollectionEntryClient struct {
	config
}

// NewCollectionEntryClient returns a client for the CollectionEntry from the given config.
func NewCollectionEntryClient(c config) *CollectionEntryClient {
	return &CollectionEntryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `collectionentry.Hooks(f(g(h())))`.
func (c *CollectionEntryClient) Use(hooks ...Hook) {
	c.hooks.CollectionEntry = append(c.hooks.CollectionEntry, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `collectionentry.Intercept(f(g(h())))`.
func (c *CollectionEntryClient) Intercept(interceptors ...Interceptor) {
	c.inters.CollectionEntry = append(c.inters.CollectionEntry, interceptors...)
}

// Create returns a builder for creating a CollectionEntry entity.
func (c *CollectionEntryClient) Create() *CollectionEntryCreate {
	mutation := newCollectionEntryMutation(c.config, OpCreate)
	return &CollectionEntryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CollectionEntry entities.
func (c *CollectionEntryClient) CreateBulk(builders ...*CollectionEntryCreate) *CollectionEntryCreateBulk {
	return &CollectionEntryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CollectionEntryClient) MapCreateBulk(slice any, setFunc func(*CollectionEntryCreate, int)) *CollectionEntryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CollectionEntryCreateBulk{err: fmt.Errorf("calling to CollectionEntryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CollectionEntryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CollectionEntryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CollectionEntry.
func (c *CollectionEntryClient) Update() *CollectionEntryUpdate {
	mutation := newCollectionEntryMutation(c.config, OpUpdate)
	return &CollectionEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CollectionEntryClient) UpdateOne(_m *CollectionEntry) *CollectionEntryUpdateOne {
	mutation := newCollectionEntryMutation(c.config, OpUpdateOne, withCollectionEntry(_m))
	return &CollectionEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CollectionEntryClient) UpdateOneID(id int64) *CollectionEntryUpdateOne {
	mutation := newCollectionEntryMutation(c.config, OpUpdateOne, withCollectionEntryID(id))
	return &CollectionEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CollectionEntry.
func (c *CollectionEntryClient) Delete() *CollectionEntryDelete {
	mutation := newCollectionEntryMutation(c.config, OpDelete)
	return &CollectionEntryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CollectionEntryClient) DeleteOne(_m *CollectionEntry) *CollectionEntryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CollectionEntryClient) DeleteOneID(id int64) *CollectionEntryDeleteOne {
	builder := c.Delete().Where(collectionentry.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CollectionEntryDeleteOne{builder}
}

// Query returns a query builder for CollectionEntry.
func (c *CollectionEntryClient) Query() *CollectionEntryQuery {
	return &CollectionEntryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCollectionEntry},
		inters: c.Interceptors(),
	}
}

// Get returns a CollectionEntry entity by its id.
func (c *CollectionEntryClient) Get(ctx context.Context, id int64) (*CollectionEntry, error) {
	return c.Query().Where(collectionentry.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CollectionEntryClient) GetX(ctx context.Context, id int64) *CollectionEntry {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CollectionEntryClient) Hooks() []Hook {
	return c.hooks.CollectionEntry
}

// Interceptors returns the client interceptors.
func (c *CollectionEntryClient) Interceptors() []Interceptor {
	return c.inters.CollectionEntry
}

func (c *CollectionEntryClient) mutate(ctx context.Context, m *CollectionEntryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CollectionEntryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CollectionEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CollectionEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CollectionEntryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CollectionEntry mutation op: %q", m.Op())
	}
}

// HistoryEventClient is a client for the HistoryEvent schema.
type HistoryEventClient struct {
	config
}

// NewHistoryEventClient returns a client for the HistoryEvent from the given config.
func NewHistoryEventClient(c config) *HistoryEventClient {
	return &HistoryEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `historyevent.Hooks(f(g(h())))`.
func (c *HistoryEventClient) Use(hooks ...Hook) {
	c.hooks.HistoryEvent = append(c.hooks.HistoryEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `historyevent.Intercept(f(g(h())))`.
func (c *HistoryEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.HistoryEvent = append(c.inters.HistoryEvent, interceptors...)
}

// Create returns a builder for creating a HistoryEvent entity.
func (c *HistoryEventClient) Create() *HistoryEventCreate {
	mutation := newHistoryEventMutation(c.config, OpCreate)
	return &HistoryEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of HistoryEvent entities.
func (c *HistoryEventClient) CreateBulk(builders ...*HistoryEventCreate) *HistoryEventCreateBulk {
	return &HistoryEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *HistoryEventClient) MapCreateBulk(slice any, setFunc func(*HistoryEventCreate, int)) *HistoryEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &HistoryEventCreateBulk{err: fmt.Errorf("calling to HistoryEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*HistoryEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &HistoryEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for HistoryEvent.
func (c *HistoryEventClient) Update() *HistoryEventUpdate {
	mutation := newHistoryEventMutation(c.config, OpUpdate)
	return &HistoryEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *HistoryEventClient) UpdateOne(_m *HistoryEvent) *HistoryEventUpdateOne {
	mutation := newHistoryEventMutation(c.config, OpUpdateOne, withHistoryEvent(_m))
	return &HistoryEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *HistoryEventClient) UpdateOneID(id int) *HistoryEventUpdateOne {
	mutation := newHistoryEventMutation(c.config, OpUpdateOne, withHistoryEventID(id))
	return &HistoryEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for HistoryEvent.
func (c *HistoryEventClient) Delete() *HistoryEventDelete {
	mutation := newHistoryEventMutation(c.config, OpDelete)
	return &HistoryEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *HistoryEventClient) DeleteOne(_m *HistoryEvent) *HistoryEventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *HistoryEventClient) DeleteOneID(id int) *HistoryEventDeleteOne {
	builder := c.Delete().Where(historyevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &HistoryEventDeleteOne{builder}
}

// Query returns a query builder for HistoryEvent.
func (c *HistoryEventClient) Query() *HistoryEventQuery {
	return &HistoryEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeHistoryEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a HistoryEvent entity by its id.
func (c *HistoryEventClient) Get(ctx context.Context, id int) (*HistoryEvent, error) {
	return c.Query().Where(historyevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *HistoryEventClient) GetX(ctx context.Context, id int) *HistoryEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *HistoryEventClient) Hooks() []Hook {
	return c.hooks.HistoryEvent
}

// Interceptors returns the client interceptors.
func (c *HistoryEventClient) Interceptors() []Interceptor {
	return c.inters.HistoryEvent
}

func (c *HistoryEventClient) mutate(ctx context.Context, m *HistoryEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&HistoryEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&HistoryEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&HistoryEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&HistoryEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown HistoryEvent mutation op: %q", m.Op())
	}
}

// JobRunClient is a client for the JobRun schema.
type JobRunClient struct {
	config
}

// NewJobRunClient returns a client for the JobRun from the given config.
func NewJobRunClient(c config) *JobRunClient {
	return &JobRunClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `jobrun.Hooks(f(g(h())))`.
func (c *JobRunClient) Use(hooks ...Hook) {
	c.hooks.JobRun = append(c.hooks.JobRun, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `jobrun.Intercept(f(g(h())))`.
func (c *JobRunClient) Intercept(interceptors ...Interceptor) {
	c.inters.JobRun = append(c.inters.JobRun, interceptors...)
}

// Create returns a builder for creating a JobRun entity.
func (c *JobRunClient) Create() *JobRunCreate {
	mutation := newJobRunMutation(c.config, OpCreate)
	return &JobRunCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of JobRun entities.
func (c *JobRunClient) CreateBulk(builders ...*JobRunCreate) *JobRunCreateBulk {
	return &JobRunCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *JobRunClient) MapCreateBulk(slice any, setFunc func(*JobRunCreate, int)) *JobRunCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &JobRunCreateBulk{err: fmt.Errorf("calling to JobRunClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*JobRunCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &JobRunCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for JobRun.
func (c *JobRunClient) Update() *JobRunUpdate {
	mutation := newJobRunMutation(c.config, OpUpdate)
	return &JobRunUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *JobRunClient) UpdateOne(_m *JobRun) *JobRunUpdateOne {
	mutation := newJobRunMutation(c.config, OpUpdateOne, withJobRun(_m))
	return &JobRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *JobRunClient) UpdateOneID(id int) *JobRunUpdateOne {
	mutation := newJobRunMutation(c.config, OpUpdateOne, withJobRunID(id))
	return &JobRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for JobRun.
func (c *JobRunClient) Delete() *JobRunDelete {
	mutation := newJobRunMutation(c.config, OpDelete)
	return &JobRunDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *JobRunClient) DeleteOne(_m *JobRun) *JobRunDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *JobRunClient) DeleteOneID(id int) *JobRunDeleteOne {
	builder := c.Delete().Where(jobrun.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &JobRunDeleteOne{builder}
}

// Query returns a query builder for JobRun.
func (c *JobRunClient) Query() *JobRunQuery {
	return &JobRunQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeJobRun},
		inters: c.Interceptors(),
	}
}

// Get returns a JobRun entity by its id.
func (c *JobRunClient) Get(ctx context.Context, id int) (*JobRun, error) {
	return c.Query().Where(jobrun.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *JobRunClient) GetX(ctx context.Context, id int) *JobRun {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *JobRunClient) Hooks() []Hook {
	return c.hooks.JobRun
}

// Interceptors returns the client interceptors.
func (c *JobRunClient) Interceptors() []Interceptor {
	return c.inters.JobRun
}

func (c *JobRunClient) mutate(ctx context.Context, m *JobRunMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&JobRunCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&JobRunUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&JobRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&JobRunDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown JobRun mutation op: %q", m.Op())
	}
}

// JobStateClient is a client for the JobState schema.
type JobStateClient struct {
	config
}

// NewJobStateClient returns a client for the JobState from the given config.
func NewJobStateClient(c config) *JobStateClient {
	return &JobStateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `jobstate.Hooks(f(g(h())))`.
func (c *JobStateClient) Use(hooks ...Hook) {
	c.hooks.JobState = append(c.hooks.JobState, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `jobstate.Intercept(f(g(h())))`.
func (c *JobStateClient) Intercept(interceptors ...Interceptor) {
	c.inters.JobState = append(c.inters.JobState, interceptors...)
}

// Create returns a builder for creating a JobState entity.
func (c *JobStateClient) Create() *JobStateCreate {
	mutation := newJobStateMutation(c.config, OpCreate)
	return &JobStateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of JobState entities.
func (c *JobStateClient) CreateBulk(builders ...*JobStateCreate) *JobStateCreateBulk {
	return &JobStateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *JobStateClient) MapCreateBulk(slice any, setFunc func(*JobStateCreate, int)) *JobStateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &JobStateCreateBulk{err: fmt.Errorf("calling to JobStateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*JobStateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &JobStateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for JobState.
func (c *JobStateClient) Update() *JobStateUpdate {
	mutation := newJobStateMutation(c.config, OpUpdate)
	return &JobStateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *JobStateClient) UpdateOne(_m *JobState) *JobStateUpdateOne {
	mutation := newJobStateMutation(c.config, OpUpdateOne, withJobState(_m))
	return &JobStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *JobStateClient) UpdateOneID(id string) *JobStateUpdateOne {
	mutation := newJobStateMutation(c.config, OpUpdateOne, withJobStateID(id))
	return &JobStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for JobState.
func (c *JobStateClient) Delete() *JobStateDelete {
	mutation := newJobStateMutation(c.config, OpDelete)
	return &JobStateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *JobStateClient) DeleteOne(_m *JobState) *JobStateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *JobStateClient) DeleteOneID(id string) *JobStateDeleteOne {
	builder := c.Delete().Where(jobstate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &JobStateDeleteOne{builder}
}

// Query returns a query builder for JobState.
func (c *JobStateClient) Query() *JobStateQuery {
	return &JobStateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeJobState},
		inters: c.Interceptors(),
	}
}

// Get returns a JobState entity by its id.
func (c *JobStateClient) Get(ctx context.Context, id string) (*JobState, error) {
	return c.Query().Where(jobstate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *JobStateClient) GetX(ctx context.Context, id string) *JobState {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *JobStateClient) Hooks() []Hook {
	return c.hooks.JobState
}

// Interceptors returns the client interceptors.
func (c *JobStateClient) Interceptors() []Interceptor {
	return c.inters.JobState
}

func (c *JobStateClient) mutate(ctx context.Context, m *JobStateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&JobStateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&JobStateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&JobStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&JobStateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown JobState mutation op: %q", m.Op())
	}
}

// ManualImportQueueClient is a client for the ManualImportQueue schema.
type ManualImportQueueClient struct {
	config
}

// NewManualImportQueueClient returns a client for the ManualImportQueue from the given config.
func NewManualImportQueueClient(c config) *ManualImportQueueClient {
	return &ManualImportQueueClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `manualimportqueue.Hooks(f(g(h())))`.
func (c *ManualImportQueueClient) Use(hooks ...Hook) {
	c.hooks.ManualImportQueue = append(c.hooks.ManualImportQueue, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `manualimportqueue.Intercept(f(g(h())))`.
func (c *ManualImportQueueClient) Intercept(interceptors ...Interceptor) {
	c.inters.ManualImportQueue = append(c.inters.ManualImportQueue, interceptors...)
}

// Create returns a builder for creating a ManualImportQueue entity.
func (c *ManualImportQueueClient) Create() *ManualImportQueueCreate {
	mutation := newManualImportQueueMutation(c.config, OpCreate)
	return &ManualImportQueueCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ManualImportQueue entities.
func (c *ManualImportQueueClient) CreateBulk(builders ...*ManualImportQueueCreate) *ManualImportQueueCreateBulk {
	return &ManualImportQueueCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ManualImportQueueClient) MapCreateBulk(slice any, setFunc func(*ManualImportQueueCreate, int)) *ManualImportQueueCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ManualImportQueueCreateBulk{err: fmt.Errorf("calling to ManualImportQueueClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ManualImportQueueCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ManualImportQueueCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ManualImportQueue.
func (c *ManualImportQueueClient) Update() *ManualImportQueueUpdate {
	mutation := newManualImportQueueMutation(c.config, OpUpdate)
	return &ManualImportQueueUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ManualImportQueueClient) UpdateOne(_m *ManualImportQueue) *ManualImportQueueUpdateOne {
	mutation := newManualImportQueueMutation(c.config, OpUpdateOne, withManualImportQueue(_m))
	return &ManualImportQueueUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ManualImportQueueClient) UpdateOneID(id int) *ManualImportQueueUpdateOne {
	mutation := newManualImportQueueMutation(c.config, OpUpdateOne, withManualImportQueueID(id))
	return &ManualImportQueueUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ManualImportQueue.
func (c *ManualImportQueueClient) Delete() *ManualImportQueueDelete {
	mutation := newManualImportQueueMutation(c.config, OpDelete)
	return &ManualImportQueueDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ManualImportQueueClient) DeleteOne(_m *ManualImportQueue) *ManualImportQueueDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ManualImportQueueClient) DeleteOneID(id int) *ManualImportQueueDeleteOne {
	builder := c.Delete().Where(manualimportqueue.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ManualImportQueueDeleteOne{builder}
}

// Query returns a query builder for ManualImportQueue.
func (c *ManualImportQueueClient) Query() *ManualImportQueueQuery {
	return &ManualImportQueueQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeManualImportQueue},
		inters: c.Interceptors(),
	}
}

// Get returns a ManualImportQueue entity by its id.
func (c *ManualImportQueueClient) Get(ctx context.Context, id int) (*ManualImportQueue, error) {
	return c.Query().Where(manualimportqueue.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ManualImportQueueClient) GetX(ctx context.Context, id int) *ManualImportQueue {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ManualImportQueueClient) Hooks() []Hook {
	return c.hooks.ManualImportQueue
}

// Interceptors returns the client interceptors.
func (c *ManualImportQueueClient) Interceptors() []Interceptor {
	return c.inters.ManualImportQueue
}

func (c *ManualImportQueueClient) mutate(ctx context.Context, m *ManualImportQueueMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ManualImportQueueCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ManualImportQueueUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ManualImportQueueUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ManualImportQueueDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ManualImportQueue mutation op: %q", m.Op())
	}
}

// PerformerClient is a client for the Performer schema.
type PerformerClient struct {
	config
}

// NewPerformerClient returns a client for the Performer from the given config.
func NewPerformerClient(c config) *PerformerClient {
	return &PerformerClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `performer.Hooks(f(g(h())))`.
func (c *PerformerClient) Use(hooks ...Hook) {
	c.hooks.Performer = append(c.hooks.Performer, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `performer.Intercept(f(g(h())))`.
func (c *PerformerClient) Intercept(interceptors ...Interceptor) {
	c.inters.Performer = append(c.inters.Performer, interceptors...)
}

// Create returns a builder for creating a Performer entity.
func (c *PerformerClient) Create() *PerformerCreate {
	mutation := newPerformerMutation(c.config, OpCreate)
	return &PerformerCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Performer entities.
func (c *PerformerClient) CreateBulk(builders ...*PerformerCreate) *PerformerCreateBulk {
	return &PerformerCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PerformerClient) MapCreateBulk(slice any, setFunc func(*PerformerCreate, int)) *PerformerCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PerformerCreateBulk{err: fmt.Errorf("calling to PerformerClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PerformerCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PerformerCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Performer.
func (c *PerformerClient) Update() *PerformerUpdate {
	mutation := newPerformerMutation(c.config, OpUpdate)
	return &PerformerUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PerformerClient) UpdateOne(_m *Performer) *PerformerUpdateOne {
	mutation := newPerformerMutation(c.config, OpUpdateOne, withPerformer(_m))
	return &PerformerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PerformerClient) UpdateOneID(id int64) *PerformerUpdateOne {
	mutation := newPerformerMutation(c.config, OpUpdateOne, withPerformerID(id))
	return &PerformerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Performer.
func (c *PerformerClient) Delete() *PerformerDelete {
	mutation := newPerformerMutation(c.config, OpDelete)
	return &PerformerDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PerformerClient) DeleteOne(_m *Performer) *PerformerDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PerformerClient) DeleteOneID(id int64) *PerformerDeleteOne {
	builder := c.Delete().Where(performer.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PerformerDeleteOne{builder}
}

// Query returns a query builder for Performer.
func (c *PerformerClient) Query() *PerformerQuery {
	return &PerformerQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePerformer},
		inters: c.Interceptors(),
	}
}

// Get returns a Performer entity by its id.
func (c *PerformerClient) Get(ctx context.Context, id int64) (*Performer, error) {
	return c.Query().Where(performer.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PerformerClient) GetX(ctx context.Context, id int64) *Performer {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PerformerClient) Hooks() []Hook {
	return c.hooks.Performer
}

// Interceptors returns the client interceptors.
func (c *PerformerClient) Interceptors() []Interceptor {
	return c.inters.Performer
}

func (c *PerformerClient) mutate(ctx context.Context, m *PerformerMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PerformerCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PerformerUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PerformerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PerformerDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Performer mutation op: %q", m.Op())
	}
}

// ProfileClient is a client for the Profile schema.
type ProfileClient struct {
	config
}

// NewProfileClient returns a client for the Profile from the given config.
func NewProfileClient(c config) *ProfileClient {
	return &ProfileClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `profile.Hooks(f(g(h())))`.
func (c *ProfileClient) Use(hooks ...Hook) {
	c.hooks.Profile = append(c.hooks.Profile, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `profile.Intercept(f(g(h())))`.
func (c *ProfileClient) Intercept(interceptors ...Interceptor) {
	c.inters.Profile = append(c.inters.Profile, interceptors...)
}

// Create returns a builder for creating a Profile entity.
func (c *ProfileClient) Create() *ProfileCreate {
	mutation := newProfileMutation(c.config, OpCreate)
	return &ProfileCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Profile entities.
func (c *ProfileClient) CreateBulk(builders ...*ProfileCreate) *ProfileCreateBulk {
	return &ProfileCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProfileClient) MapCreateBulk(slice any, setFunc func(*ProfileCreate, int)) *ProfileCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProfileCreateBulk{err: fmt.Errorf("calling to ProfileClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProfileCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProfileCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Profile.
func (c *ProfileClient) Update() *ProfileUpdate {
	mutation := newProfileMutation(c.config, OpUpdate)
	return &ProfileUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProfileClient) UpdateOne(_m *Profile) *ProfileUpdateOne {
	mutation := newProfileMutation(c.config, OpUpdateOne, withProfile(_m))
	return &ProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProfileClient) UpdateOneID(id int) *ProfileUpdateOne {
	mutation := newProfileMutation(c.config, OpUpdateOne, withProfileID(id))
	return &ProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Profile.
func (c *ProfileClient) Delete() *ProfileDelete {
	mutation := newProfileMutation(c.config, OpDelete)
	return &ProfileDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProfileClient) DeleteOne(_m *Profile) *ProfileDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProfileClient) DeleteOneID(id int) *ProfileDeleteOne {
	builder := c.Delete().Where(profile.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProfileDeleteOne{builder}
}

// Query returns a query builder for Profile.
func (c *ProfileClient) Query() *ProfileQuery {
	return &ProfileQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProfile},
		inters: c.Interceptors(),
	}
}

// Get returns a Profile entity by its id.
func (c *ProfileClient) Get(ctx context.Context, id int) (*Profile, error) {
	return c.Query().Where(profile.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProfileClient) GetX(ctx context.Context, id int) *Profile {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ProfileClient) Hooks() []Hook {
	return c.hooks.Profile
}

// Interceptors returns the client interceptors.
func (c *ProfileClient) Interceptors() []Interceptor {
	return c.inters.Profile
}

func (c *ProfileClient) mutate(ctx context.Context, m *ProfileMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProfileCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProfileUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProfileDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Profile mutation op: %q", m.Op())
	}
}

// RecordingClient is a client for the Recording schema.
type RecordingClient struct {
	config
}

// NewRecordingClient returns a client for the Recording from the given config.
func NewRecordingClient(c config) *RecordingClient {
	return &RecordingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `recording.Hooks(f(g(h())))`.
func (c *RecordingClient) Use(hooks ...Hook) {
	c.hooks.Recording = append(c.hooks.Recording, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `recording.Intercept(f(g(h())))`.
func (c *RecordingClient) Intercept(interceptors ...Interceptor) {
	c.inters.Recording = append(c.inters.Recording, interceptors...)
}

// Create returns a builder for creating a Recording entity.
func (c *RecordingClient) Create() *RecordingCreate {
	mutation := newRecordingMutation(c.config, OpCreate)
	return &RecordingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Recording entities.
func (c *RecordingClient) CreateBulk(builders ...*RecordingCreate) *RecordingCreateBulk {
	return &RecordingCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RecordingClient) MapCreateBulk(slice any, setFunc func(*RecordingCreate, int)) *RecordingCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RecordingCreateBulk{err: fmt.Errorf("calling to RecordingClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RecordingCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RecordingCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Recording.
func (c *RecordingClient) Update() *RecordingUpdate {
	mutation := newRecordingMutation(c.config, OpUpdate)
	return &RecordingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RecordingClient) UpdateOne(_m *Recording) *RecordingUpdateOne {
	mutation := newRecordingMutation(c.config, OpUpdateOne, withRecording(_m))
	return &RecordingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RecordingClient) UpdateOneID(id int64) *RecordingUpdateOne {
	mutation := newRecordingMutation(c.config, OpUpdateOne, withRecordingID(id))
	return &RecordingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Recording.
func (c *RecordingClient) Delete() *RecordingDelete {
	mutation := newRecordingMutation(c.config, OpDelete)
	return &RecordingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RecordingClient) DeleteOne(_m *Recording) *RecordingDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RecordingClient) DeleteOneID(id int64) *RecordingDeleteOne {
	builder := c.Delete().Where(recording.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RecordingDeleteOne{builder}
}

// Query returns a query builder for Recording.
func (c *RecordingClient) Query() *RecordingQuery {
	return &RecordingQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRecording},
		inters: c.Interceptors(),
	}
}

// Get returns a Recording entity by its id.
func (c *RecordingClient) Get(ctx context.Context, id int64) (*Recording, error) {
	return c.Query().Where(recording.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RecordingClient) GetX(ctx context.Context, id int64) *Recording {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryShow queries the show edge of a Recording.
func (c *RecordingClient) QueryShow(_m *Recording) *ShowQuery {
	query := (&ShowClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(recording.Table, recording.FieldID, id),
			sqlgraph.To(show.Table, show.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, recording.ShowTable, recording.ShowColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCastEntries queries the cast_entries edge of a Recording.
func (c *RecordingClient) QueryCastEntries(_m *Recording) *CastEntryQuery {
	query := (&CastEntryClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(recording.Table, recording.FieldID, id),
			sqlgraph.To(castentry.Table, castentry.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, recording.CastEntriesTable, recording.CastEntriesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryVersions queries the versions edge of a Recording.
func (c *RecordingClient) QueryVersions(_m *Recording) *RecordingVersionQuery {
	query := (&RecordingVersionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(recording.Table, recording.FieldID, id),
			sqlgraph.To(recordingversion.Table, recordingversion.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, recording.VersionsTable, recording.VersionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RecordingClient) Hooks() []Hook {
	return c.hooks.Recording
}

// Interceptors returns the client interceptors.
func (c *RecordingClient) Interceptors() []Interceptor {
	return c.inters.Recording
}

func (c *RecordingClient) mutate(ctx context.Context, m *RecordingMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RecordingCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RecordingUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RecordingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RecordingDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Recording mutation op: %q", m.Op())
	}
}

// RecordingImageChoiceClient is a client for the RecordingImageChoice schema.
type RecordingImageChoiceClient struct {
	config
}

// NewRecordingImageChoiceClient returns a client for the RecordingImageChoice from the given config.
func NewRecordingImageChoiceClient(c config) *RecordingImageChoiceClient {
	return &RecordingImageChoiceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `recordingimagechoice.Hooks(f(g(h())))`.
func (c *RecordingImageChoiceClient) Use(hooks ...Hook) {
	c.hooks.RecordingImageChoice = append(c.hooks.RecordingImageChoice, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `recordingimagechoice.Intercept(f(g(h())))`.
func (c *RecordingImageChoiceClient) Intercept(interceptors ...Interceptor) {
	c.inters.RecordingImageChoice = append(c.inters.RecordingImageChoice, interceptors...)
}

// Create returns a builder for creating a RecordingImageChoice entity.
func (c *RecordingImageChoiceClient) Create() *RecordingImageChoiceCreate {
	mutation := newRecordingImageChoiceMutation(c.config, OpCreate)
	return &RecordingImageChoiceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RecordingImageChoice entities.
func (c *RecordingImageChoiceClient) CreateBulk(builders ...*RecordingImageChoiceCreate) *RecordingImageChoiceCreateBulk {
	return &RecordingImageChoiceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RecordingImageChoiceClient) MapCreateBulk(slice any, setFunc func(*RecordingImageChoiceCreate, int)) *RecordingImageChoiceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RecordingImageChoiceCreateBulk{err: fmt.Errorf("calling to RecordingImageChoiceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RecordingImageChoiceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RecordingImageChoiceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RecordingImageChoice.
func (c *RecordingImageChoiceClient) Update() *RecordingImageChoiceUpdate {
	mutation := newRecordingImageChoiceMutation(c.config, OpUpdate)
	return &RecordingImageChoiceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RecordingImageChoiceClient) UpdateOne(_m *RecordingImageChoice) *RecordingImageChoiceUpdateOne {
	mutation := newRecordingImageChoiceMutation(c.config, OpUpdateOne, withRecordingImageChoice(_m))
	return &RecordingImageChoiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RecordingImageChoiceClient) UpdateOneID(id int64) *RecordingImageChoiceUpdateOne {
	mutation := newRecordingImageChoiceMutation(c.config, OpUpdateOne, withRecordingImageChoiceID(id))
	return &RecordingImageChoiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RecordingImageChoice.
func (c *RecordingImageChoiceClient) Delete() *RecordingImageChoiceDelete {
	mutation := newRecordingImageChoiceMutation(c.config, OpDelete)
	return &RecordingImageChoiceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RecordingImageChoiceClient) DeleteOne(_m *RecordingImageChoice) *RecordingImageChoiceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RecordingImageChoiceClient) DeleteOneID(id int64) *RecordingImageChoiceDeleteOne {
	builder := c.Delete().Where(recordingimagechoice.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RecordingImageChoiceDeleteOne{builder}
}

// Query returns a query builder for RecordingImageChoice.
func (c *RecordingImageChoiceClient) Query() *RecordingImageChoiceQuery {
	return &RecordingImageChoiceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRecordingImageChoice},
		inters: c.Interceptors(),
	}
}

// Get returns a RecordingImageChoice entity by its id.
func (c *RecordingImageChoiceClient) Get(ctx context.Context, id int64) (*RecordingImageChoice, error) {
	return c.Query().Where(recordingimagechoice.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RecordingImageChoiceClient) GetX(ctx context.Context, id int64) *RecordingImageChoice {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RecordingImageChoiceClient) Hooks() []Hook {
	return c.hooks.RecordingImageChoice
}

// Interceptors returns the client interceptors.
func (c *RecordingImageChoiceClient) Interceptors() []Interceptor {
	return c.inters.RecordingImageChoice
}

func (c *RecordingImageChoiceClient) mutate(ctx context.Context, m *RecordingImageChoiceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RecordingImageChoiceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RecordingImageChoiceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RecordingImageChoiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RecordingImageChoiceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RecordingImageChoice mutation op: %q", m.Op())
	}
}

// RecordingVersionClient is a client for the RecordingVersion schema.
type RecordingVersionClient struct {
	config
}

// NewRecordingVersionClient returns a client for the RecordingVersion from the given config.
func NewRecordingVersionClient(c config) *RecordingVersionClient {
	return &RecordingVersionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `recordingversion.Hooks(f(g(h())))`.
func (c *RecordingVersionClient) Use(hooks ...Hook) {
	c.hooks.RecordingVersion = append(c.hooks.RecordingVersion, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `recordingversion.Intercept(f(g(h())))`.
func (c *RecordingVersionClient) Intercept(interceptors ...Interceptor) {
	c.inters.RecordingVersion = append(c.inters.RecordingVersion, interceptors...)
}

// Create returns a builder for creating a RecordingVersion entity.
func (c *RecordingVersionClient) Create() *RecordingVersionCreate {
	mutation := newRecordingVersionMutation(c.config, OpCreate)
	return &RecordingVersionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RecordingVersion entities.
func (c *RecordingVersionClient) CreateBulk(builders ...*RecordingVersionCreate) *RecordingVersionCreateBulk {
	return &RecordingVersionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RecordingVersionClient) MapCreateBulk(slice any, setFunc func(*RecordingVersionCreate, int)) *RecordingVersionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RecordingVersionCreateBulk{err: fmt.Errorf("calling to RecordingVersionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RecordingVersionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RecordingVersionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RecordingVersion.
func (c *RecordingVersionClient) Update() *RecordingVersionUpdate {
	mutation := newRecordingVersionMutation(c.config, OpUpdate)
	return &RecordingVersionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RecordingVersionClient) UpdateOne(_m *RecordingVersion) *RecordingVersionUpdateOne {
	mutation := newRecordingVersionMutation(c.config, OpUpdateOne, withRecordingVersion(_m))
	return &RecordingVersionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RecordingVersionClient) UpdateOneID(id int) *RecordingVersionUpdateOne {
	mutation := newRecordingVersionMutation(c.config, OpUpdateOne, withRecordingVersionID(id))
	return &RecordingVersionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RecordingVersion.
func (c *RecordingVersionClient) Delete() *RecordingVersionDelete {
	mutation := newRecordingVersionMutation(c.config, OpDelete)
	return &RecordingVersionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RecordingVersionClient) DeleteOne(_m *RecordingVersion) *RecordingVersionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RecordingVersionClient) DeleteOneID(id int) *RecordingVersionDeleteOne {
	builder := c.Delete().Where(recordingversion.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RecordingVersionDeleteOne{builder}
}

// Query returns a query builder for RecordingVersion.
func (c *RecordingVersionClient) Query() *RecordingVersionQuery {
	return &RecordingVersionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRecordingVersion},
		inters: c.Interceptors(),
	}
}

// Get returns a RecordingVersion entity by its id.
func (c *RecordingVersionClient) Get(ctx context.Context, id int) (*RecordingVersion, error) {
	return c.Query().Where(recordingversion.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RecordingVersionClient) GetX(ctx context.Context, id int) *RecordingVersion {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRecording queries the recording edge of a RecordingVersion.
func (c *RecordingVersionClient) QueryRecording(_m *RecordingVersion) *RecordingQuery {
	query := (&RecordingClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(recordingversion.Table, recordingversion.FieldID, id),
			sqlgraph.To(recording.Table, recording.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, recordingversion.RecordingTable, recordingversion.RecordingColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RecordingVersionClient) Hooks() []Hook {
	return c.hooks.RecordingVersion
}

// Interceptors returns the client interceptors.
func (c *RecordingVersionClient) Interceptors() []Interceptor {
	return c.inters.RecordingVersion
}

func (c *RecordingVersionClient) mutate(ctx context.Context, m *RecordingVersionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RecordingVersionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RecordingVersionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RecordingVersionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RecordingVersionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RecordingVersion mutation op: %q", m.Op())
	}
}

// ShowClient is a client for the Show schema.
type ShowClient struct {
	config
}

// NewShowClient returns a client for the Show from the given config.
func NewShowClient(c config) *ShowClient {
	return &ShowClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `show.Hooks(f(g(h())))`.
func (c *ShowClient) Use(hooks ...Hook) {
	c.hooks.Show = append(c.hooks.Show, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `show.Intercept(f(g(h())))`.
func (c *ShowClient) Intercept(interceptors ...Interceptor) {
	c.inters.Show = append(c.inters.Show, interceptors...)
}

// Create returns a builder for creating a Show entity.
func (c *ShowClient) Create() *ShowCreate {
	mutation := newShowMutation(c.config, OpCreate)
	return &ShowCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Show entities.
func (c *ShowClient) CreateBulk(builders ...*ShowCreate) *ShowCreateBulk {
	return &ShowCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ShowClient) MapCreateBulk(slice any, setFunc func(*ShowCreate, int)) *ShowCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ShowCreateBulk{err: fmt.Errorf("calling to ShowClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ShowCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ShowCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Show.
func (c *ShowClient) Update() *ShowUpdate {
	mutation := newShowMutation(c.config, OpUpdate)
	return &ShowUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ShowClient) UpdateOne(_m *Show) *ShowUpdateOne {
	mutation := newShowMutation(c.config, OpUpdateOne, withShow(_m))
	return &ShowUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ShowClient) UpdateOneID(id int64) *ShowUpdateOne {
	mutation := newShowMutation(c.config, OpUpdateOne, withShowID(id))
	return &ShowUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Show.
func (c *ShowClient) Delete() *ShowDelete {
	mutation := newShowMutation(c.config, OpDelete)
	return &ShowDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ShowClient) DeleteOne(_m *Show) *ShowDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ShowClient) DeleteOneID(id int64) *ShowDeleteOne {
	builder := c.Delete().Where(show.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ShowDeleteOne{builder}
}

// Query returns a query builder for Show.
func (c *ShowClient) Query() *ShowQuery {
	return &ShowQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeShow},
		inters: c.Interceptors(),
	}
}

// Get returns a Show entity by its id.
func (c *ShowClient) Get(ctx context.Context, id int64) (*Show, error) {
	return c.Query().Where(show.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ShowClient) GetX(ctx context.Context, id int64) *Show {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRecordings queries the recordings edge of a Show.
func (c *ShowClient) QueryRecordings(_m *Show) *RecordingQuery {
	query := (&RecordingClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(show.Table, show.FieldID, id),
			sqlgraph.To(recording.Table, recording.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, show.RecordingsTable, show.RecordingsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ShowClient) Hooks() []Hook {
	return c.hooks.Show
}

// Interceptors returns the client interceptors.
func (c *ShowClient) Interceptors() []Interceptor {
	return c.inters.Show
}

func (c *ShowClient) mutate(ctx context.Context, m *ShowMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ShowCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ShowUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ShowUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ShowDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Show mutation op: %q", m.Op())
	}
}

// SyncRunClient is a client for the SyncRun schema.
type SyncRunClient struct {
	config
}

// NewSyncRunClient returns a client for the SyncRun from the given config.
func NewSyncRunClient(c config) *SyncRunClient {
	return &SyncRunClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `syncrun.Hooks(f(g(h())))`.
func (c *SyncRunClient) Use(hooks ...Hook) {
	c.hooks.SyncRun = append(c.hooks.SyncRun, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `syncrun.Intercept(f(g(h())))`.
func (c *SyncRunClient) Intercept(interceptors ...Interceptor) {
	c.inters.SyncRun = append(c.inters.SyncRun, interceptors...)
}

// Create returns a builder for creating a SyncRun entity.
func (c *SyncRunClient) Create() *SyncRunCreate {
	mutation := newSyncRunMutation(c.config, OpCreate)
	return &SyncRunCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SyncRun entities.
func (c *SyncRunClient) CreateBulk(builders ...*SyncRunCreate) *SyncRunCreateBulk {
	return &SyncRunCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SyncRunClient) MapCreateBulk(slice any, setFunc func(*SyncRunCreate, int)) *SyncRunCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SyncRunCreateBulk{err: fmt.Errorf("calling to SyncRunClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SyncRunCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SyncRunCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SyncRun.
func (c *SyncRunClient) Update() *SyncRunUpdate {
	mutation := newSyncRunMutation(c.config, OpUpdate)
	return &SyncRunUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SyncRunClient) UpdateOne(_m *SyncRun) *SyncRunUpdateOne {
	mutation := newSyncRunMutation(c.config, OpUpdateOne, withSyncRun(_m))
	return &SyncRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SyncRunClient) UpdateOneID(id int) *SyncRunUpdateOne {
	mutation := newSyncRunMutation(c.config, OpUpdateOne, withSyncRunID(id))
	return &SyncRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SyncRun.
func (c *SyncRunClient) Delete() *SyncRunDelete {
	mutation := newSyncRunMutation(c.config, OpDelete)
	return &SyncRunDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SyncRunClient) DeleteOne(_m *SyncRun) *SyncRunDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SyncRunClient) DeleteOneID(id int) *SyncRunDeleteOne {
	builder := c.Delete().Where(syncrun.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SyncRunDeleteOne{builder}
}

// Query returns a query builder for SyncRun.
func (c *SyncRunClient) Query() *SyncRunQuery {
	return &SyncRunQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSyncRun},
		inters: c.Interceptors(),
	}
}

// Get returns a SyncRun entity by its id.
func (c *SyncRunClient) Get(ctx context.Context, id int) (*SyncRun, error) {
	return c.Query().Where(syncrun.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SyncRunClient) GetX(ctx context.Context, id int) *SyncRun {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SyncRunClient) Hooks() []Hook {
	return c.hooks.SyncRun
}

// Interceptors returns the client interceptors.
func (c *SyncRunClient) Interceptors() []Interceptor {
	return c.inters.SyncRun
}

func (c *SyncRunClient) mutate(ctx context.Context, m *SyncRunMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SyncRunCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SyncRunUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SyncRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SyncRunDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SyncRun mutation op: %q", m.Op())
	}
}

// WantsEntryClient is a client for the WantsEntry schema.
type WantsEntryClient struct {
	config
}

// NewWantsEntryClient returns a client for the WantsEntry from the given config.
func NewWantsEntryClient(c config) *WantsEntryClient {
	return &WantsEntryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `wantsentry.Hooks(f(g(h())))`.
func (c *WantsEntryClient) Use(hooks ...Hook) {
	c.hooks.WantsEntry = append(c.hooks.WantsEntry, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `wantsentry.Intercept(f(g(h())))`.
func (c *WantsEntryClient) Intercept(interceptors ...Interceptor) {
	c.inters.WantsEntry = append(c.inters.WantsEntry, interceptors...)
}

// Create returns a builder for creating a WantsEntry entity.
func (c *WantsEntryClient) Create() *WantsEntryCreate {
	mutation := newWantsEntryMutation(c.config, OpCreate)
	return &WantsEntryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of WantsEntry entities.
func (c *WantsEntryClient) CreateBulk(builders ...*WantsEntryCreate) *WantsEntryCreateBulk {
	return &WantsEntryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WantsEntryClient) MapCreateBulk(slice any, setFunc func(*WantsEntryCreate, int)) *WantsEntryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WantsEntryCreateBulk{err: fmt.Errorf("calling to WantsEntryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WantsEntryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WantsEntryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for WantsEntry.
func (c *WantsEntryClient) Update() *WantsEntryUpdate {
	mutation := newWantsEntryMutation(c.config, OpUpdate)
	return &WantsEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WantsEntryClient) UpdateOne(_m *WantsEntry) *WantsEntryUpdateOne {
	mutation := newWantsEntryMutation(c.config, OpUpdateOne, withWantsEntry(_m))
	return &WantsEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WantsEntryClient) UpdateOneID(id int64) *WantsEntryUpdateOne {
	mutation := newWantsEntryMutation(c.config, OpUpdateOne, withWantsEntryID(id))
	return &WantsEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for WantsEntry.
func (c *WantsEntryClient) Delete() *WantsEntryDelete {
	mutation := newWantsEntryMutation(c.config, OpDelete)
	return &WantsEntryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WantsEntryClient) DeleteOne(_m *WantsEntry) *WantsEntryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WantsEntryClient) DeleteOneID(id int64) *WantsEntryDeleteOne {
	builder := c.Delete().Where(wantsentry.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WantsEntryDeleteOne{builder}
}

// Query returns a query builder for WantsEntry.
func (c *WantsEntryClient) Query() *WantsEntryQuery {
	return &WantsEntryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWantsEntry},
		inters: c.Interceptors(),
	}
}

// Get returns a WantsEntry entity by its id.
func (c *WantsEntryClient) Get(ctx context.Context, id int64) (*WantsEntry, error) {
	return c.Query().Where(wantsentry.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WantsEntryClient) GetX(ctx context.Context, id int64) *WantsEntry {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *WantsEntryClient) Hooks() []Hook {
	return c.hooks.WantsEntry
}

// Interceptors returns the client interceptors.
func (c *WantsEntryClient) Interceptors() []Interceptor {
	return c.inters.WantsEntry
}

func (c *WantsEntryClient) mutate(ctx context.Context, m *WantsEntryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WantsEntryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WantsEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WantsEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WantsEntryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown WantsEntry mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		CastEntry, Character, CollectionEntry, HistoryEvent, JobRun, JobState,
		ManualImportQueue, Performer, Profile, Recording, RecordingImageChoice,
		RecordingVersion, Show, SyncRun, WantsEntry []ent.Hook
	}
	inters struct {
		CastEntry, Character, CollectionEntry, HistoryEvent, JobRun, JobState,
		ManualImportQueue, Performer, Profile, Recording, RecordingImageChoice,
		RecordingVersion, Show, SyncRun, WantsEntry []ent.Interceptor
	}
)
