// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nicolerenee/promptbook/internal/ent/collectionentry"
)

// CollectionEntryCreate is the builder for creating a CollectionEntry entity.
type CollectionEntryCreate struct {
	config
	mutation *CollectionEntryMutation
	hooks    []Hook
}

// SetFormat sets the "format" field.
func (_c *CollectionEntryCreate) SetFormat(v string) *CollectionEntryCreate {
	_c.mutation.SetFormat(v)
	return _c
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (_c *CollectionEntryCreate) SetNillableFormat(v *string) *CollectionEntryCreate {
	if v != nil {
		_c.SetFormat(*v)
	}
	return _c
}

// SetUserNotes sets the "user_notes" field.
func (_c *CollectionEntryCreate) SetUserNotes(v string) *CollectionEntryCreate {
	_c.mutation.SetUserNotes(v)
	return _c
}

// SetNillableUserNotes sets the "user_notes" field if the given value is not nil.
func (_c *CollectionEntryCreate) SetNillableUserNotes(v *string) *CollectionEntryCreate {
	if v != nil {
		_c.SetUserNotes(*v)
	}
	return _c
}

// SetUserWatched sets the "user_watched" field.
func (_c *CollectionEntryCreate) SetUserWatched(v bool) *CollectionEntryCreate {
	_c.mutation.SetUserWatched(v)
	return _c
}

// SetNillableUserWatched sets the "user_watched" field if the given value is not nil.
func (_c *CollectionEntryCreate) SetNillableUserWatched(v *bool) *CollectionEntryCreate {
	if v != nil {
		_c.SetUserWatched(*v)
	}
	return _c
}

// SetCollectedAt sets the "collected_at" field.
func (_c *CollectionEntryCreate) SetCollectedAt(v time.Time) *CollectionEntryCreate {
	_c.mutation.SetCollectedAt(v)
	return _c
}

// SetNillableCollectedAt sets the "collected_at" field if the given value is not nil.
func (_c *CollectionEntryCreate) SetNillableCollectedAt(v *time.Time) *CollectionEntryCreate {
	if v != nil {
		_c.SetCollectedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CollectionEntryCreate) SetUpdatedAt(v time.Time) *CollectionEntryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CollectionEntryCreate) SetNillableUpdatedAt(v *time.Time) *CollectionEntryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_c *CollectionEntryCreate) SetLastSyncedAt(v time.Time) *CollectionEntryCreate {
	_c.mutation.SetLastSyncedAt(v)
	return _c
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_c *CollectionEntryCreate) SetNillableLastSyncedAt(v *time.Time) *CollectionEntryCreate {
	if v != nil {
		_c.SetLastSyncedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CollectionEntryCreate) SetID(v int64) *CollectionEntryCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the CollectionEntryMutation object of the builder.
func (_c *CollectionEntryCreate) Mutation() *CollectionEntryMutation {
	return _c.mutation
}

// Save creates the CollectionEntry in the database.
func (_c *CollectionEntryCreate) Save(ctx context.Context) (*CollectionEntry, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CollectionEntryCreate) SaveX(ctx context.Context) *CollectionEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CollectionEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CollectionEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CollectionEntryCreate) defaults() {
	if _, ok := _c.mutation.Format(); !ok {
		v := collectionentry.DefaultFormat
		_c.mutation.SetFormat(v)
	}
	if _, ok := _c.mutation.UserWatched(); !ok {
		v := collectionentry.DefaultUserWatched
		_c.mutation.SetUserWatched(v)
	}
	if _, ok := _c.mutation.LastSyncedAt(); !ok {
		v := collectionentry.DefaultLastSyncedAt()
		_c.mutation.SetLastSyncedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CollectionEntryCreate) check() error {
	if _, ok := _c.mutation.Format(); !ok {
		return &ValidationError{Name: "format", err: errors.New(`ent: missing required field "CollectionEntry.format"`)}
	}
	if _, ok := _c.mutation.UserWatched(); !ok {
		return &ValidationError{Name: "user_watched", err: errors.New(`ent: missing required field "CollectionEntry.user_watched"`)}
	}
	if _, ok := _c.mutation.LastSyncedAt(); !ok {
		return &ValidationError{Name: "last_synced_at", err: errors.New(`ent: missing required field "CollectionEntry.last_synced_at"`)}
	}
	return nil
}

func (_c *CollectionEntryCreate) sqlSave(ctx context.Context) (*CollectionEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CollectionEntryCreate) createSpec() (*CollectionEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &CollectionEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(collectionentry.Table, sqlgraph.NewFieldSpec(collectionentry.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Format(); ok {
		_spec.SetField(collectionentry.FieldFormat, field.TypeString, value)
		_node.Format = value
	}
	if value, ok := _c.mutation.UserNotes(); ok {
		_spec.SetField(collectionentry.FieldUserNotes, field.TypeString, value)
		_node.UserNotes = &value
	}
	if value, ok := _c.mutation.UserWatched(); ok {
		_spec.SetField(collectionentry.FieldUserWatched, field.TypeBool, value)
		_node.UserWatched = value
	}
	if value, ok := _c.mutation.CollectedAt(); ok {
		_spec.SetField(collectionentry.FieldCollectedAt, field.TypeTime, value)
		_node.CollectedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(collectionentry.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.LastSyncedAt(); ok {
		_spec.SetField(collectionentry.FieldLastSyncedAt, field.TypeTime, value)
		_node.LastSyncedAt = value
	}
	return _node, _spec
}

// CollectionEntryCreateBulk is the builder for creating many CollectionEntry entities in bulk.
type CollectionEntryCreateBulk struct {
	config
	err      error
	builders []*CollectionEntryCreate
}

// Save creates the CollectionEntry entities in the database.
func (_c *CollectionEntryCreateBulk) Save(ctx context.Context) ([]*CollectionEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CollectionEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CollectionEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CollectionEntryCreateBulk) SaveX(ctx context.Context) []*CollectionEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CollectionEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CollectionEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
