// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nicolerenee/promptbook/internal/ent/extraentry"
	"github.com/nicolerenee/promptbook/internal/ent/predicate"
	"github.com/nicolerenee/promptbook/internal/ent/recording"
)

// ExtraEntryUpdate is the builder for updating ExtraEntry entities.
type ExtraEntryUpdate struct {
	config
	hooks     []Hook
	mutation  *ExtraEntryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ExtraEntryUpdate builder.
func (_u *ExtraEntryUpdate) Where(ps ...predicate.ExtraEntry) *ExtraEntryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRecordingID sets the "recording_id" field.
func (_u *ExtraEntryUpdate) SetRecordingID(v int64) *ExtraEntryUpdate {
	_u.mutation.SetRecordingID(v)
	return _u
}

// SetNillableRecordingID sets the "recording_id" field if the given value is not nil.
func (_u *ExtraEntryUpdate) SetNillableRecordingID(v *int64) *ExtraEntryUpdate {
	if v != nil {
		_u.SetRecordingID(*v)
	}
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *ExtraEntryUpdate) SetFilePath(v string) *ExtraEntryUpdate {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *ExtraEntryUpdate) SetNillableFilePath(v *string) *ExtraEntryUpdate {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *ExtraEntryUpdate) SetKind(v string) *ExtraEntryUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ExtraEntryUpdate) SetNillableKind(v *string) *ExtraEntryUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *ExtraEntryUpdate) SetLabel(v string) *ExtraEntryUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *ExtraEntryUpdate) SetNillableLabel(v *string) *ExtraEntryUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetFileSizeBytes sets the "file_size_bytes" field.
func (_u *ExtraEntryUpdate) SetFileSizeBytes(v int64) *ExtraEntryUpdate {
	_u.mutation.ResetFileSizeBytes()
	_u.mutation.SetFileSizeBytes(v)
	return _u
}

// SetNillableFileSizeBytes sets the "file_size_bytes" field if the given value is not nil.
func (_u *ExtraEntryUpdate) SetNillableFileSizeBytes(v *int64) *ExtraEntryUpdate {
	if v != nil {
		_u.SetFileSizeBytes(*v)
	}
	return _u
}

// AddFileSizeBytes adds value to the "file_size_bytes" field.
func (_u *ExtraEntryUpdate) AddFileSizeBytes(v int64) *ExtraEntryUpdate {
	_u.mutation.AddFileSizeBytes(v)
	return _u
}

// SetAddedAt sets the "added_at" field.
func (_u *ExtraEntryUpdate) SetAddedAt(v time.Time) *ExtraEntryUpdate {
	_u.mutation.SetAddedAt(v)
	return _u
}

// SetNillableAddedAt sets the "added_at" field if the given value is not nil.
func (_u *ExtraEntryUpdate) SetNillableAddedAt(v *time.Time) *ExtraEntryUpdate {
	if v != nil {
		_u.SetAddedAt(*v)
	}
	return _u
}

// SetRecording sets the "recording" edge to the Recording entity.
func (_u *ExtraEntryUpdate) SetRecording(v *Recording) *ExtraEntryUpdate {
	return _u.SetRecordingID(v.ID)
}

// Mutation returns the ExtraEntryMutation object of the builder.
func (_u *ExtraEntryUpdate) Mutation() *ExtraEntryMutation {
	return _u.mutation
}

// ClearRecording clears the "recording" edge to the Recording entity.
func (_u *ExtraEntryUpdate) ClearRecording() *ExtraEntryUpdate {
	_u.mutation.ClearRecording()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ExtraEntryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExtraEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ExtraEntryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExtraEntryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExtraEntryUpdate) check() error {
	if _u.mutation.RecordingCleared() && len(_u.mutation.RecordingIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ExtraEntry.recording"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ExtraEntryUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ExtraEntryUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ExtraEntryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(extraentry.Table, extraentry.Columns, sqlgraph.NewFieldSpec(extraentry.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(extraentry.FieldFilePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(extraentry.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(extraentry.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSizeBytes(); ok {
		_spec.SetField(extraentry.FieldFileSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSizeBytes(); ok {
		_spec.AddField(extraentry.FieldFileSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAt(); ok {
		_spec.SetField(extraentry.FieldAddedAt, field.TypeTime, value)
	}
	if _u.mutation.RecordingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   extraentry.RecordingTable,
			Columns: []string{extraentry.RecordingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recording.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecordingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   extraentry.RecordingTable,
			Columns: []string{extraentry.RecordingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recording.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{extraentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ExtraEntryUpdateOne is the builder for updating a single ExtraEntry entity.
type ExtraEntryUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ExtraEntryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetRecordingID sets the "recording_id" field.
func (_u *ExtraEntryUpdateOne) SetRecordingID(v int64) *ExtraEntryUpdateOne {
	_u.mutation.SetRecordingID(v)
	return _u
}

// SetNillableRecordingID sets the "recording_id" field if the given value is not nil.
func (_u *ExtraEntryUpdateOne) SetNillableRecordingID(v *int64) *ExtraEntryUpdateOne {
	if v != nil {
		_u.SetRecordingID(*v)
	}
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *ExtraEntryUpdateOne) SetFilePath(v string) *ExtraEntryUpdateOne {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *ExtraEntryUpdateOne) SetNillableFilePath(v *string) *ExtraEntryUpdateOne {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *ExtraEntryUpdateOne) SetKind(v string) *ExtraEntryUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ExtraEntryUpdateOne) SetNillableKind(v *string) *ExtraEntryUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *ExtraEntryUpdateOne) SetLabel(v string) *ExtraEntryUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *ExtraEntryUpdateOne) SetNillableLabel(v *string) *ExtraEntryUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetFileSizeBytes sets the "file_size_bytes" field.
func (_u *ExtraEntryUpdateOne) SetFileSizeBytes(v int64) *ExtraEntryUpdateOne {
	_u.mutation.ResetFileSizeBytes()
	_u.mutation.SetFileSizeBytes(v)
	return _u
}

// SetNillableFileSizeBytes sets the "file_size_bytes" field if the given value is not nil.
func (_u *ExtraEntryUpdateOne) SetNillableFileSizeBytes(v *int64) *ExtraEntryUpdateOne {
	if v != nil {
		_u.SetFileSizeBytes(*v)
	}
	return _u
}

// AddFileSizeBytes adds value to the "file_size_bytes" field.
func (_u *ExtraEntryUpdateOne) AddFileSizeBytes(v int64) *ExtraEntryUpdateOne {
	_u.mutation.AddFileSizeBytes(v)
	return _u
}

// SetAddedAt sets the "added_at" field.
func (_u *ExtraEntryUpdateOne) SetAddedAt(v time.Time) *ExtraEntryUpdateOne {
	_u.mutation.SetAddedAt(v)
	return _u
}

// SetNillableAddedAt sets the "added_at" field if the given value is not nil.
func (_u *ExtraEntryUpdateOne) SetNillableAddedAt(v *time.Time) *ExtraEntryUpdateOne {
	if v != nil {
		_u.SetAddedAt(*v)
	}
	return _u
}

// SetRecording sets the "recording" edge to the Recording entity.
func (_u *ExtraEntryUpdateOne) SetRecording(v *Recording) *ExtraEntryUpdateOne {
	return _u.SetRecordingID(v.ID)
}

// Mutation returns the ExtraEntryMutation object of the builder.
func (_u *ExtraEntryUpdateOne) Mutation() *ExtraEntryMutation {
	return _u.mutation
}

// ClearRecording clears the "recording" edge to the Recording entity.
func (_u *ExtraEntryUpdateOne) ClearRecording() *ExtraEntryUpdateOne {
	_u.mutation.ClearRecording()
	return _u
}

// Where appends a list predicates to the ExtraEntryUpdate builder.
func (_u *ExtraEntryUpdateOne) Where(ps ...predicate.ExtraEntry) *ExtraEntryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ExtraEntryUpdateOne) Select(field string, fields ...string) *ExtraEntryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ExtraEntry entity.
func (_u *ExtraEntryUpdateOne) Save(ctx context.Context) (*ExtraEntry, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExtraEntryUpdateOne) SaveX(ctx context.Context) *ExtraEntry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ExtraEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExtraEntryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExtraEntryUpdateOne) check() error {
	if _u.mutation.RecordingCleared() && len(_u.mutation.RecordingIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ExtraEntry.recording"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ExtraEntryUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ExtraEntryUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ExtraEntryUpdateOne) sqlSave(ctx context.Context) (_node *ExtraEntry, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(extraentry.Table, extraentry.Columns, sqlgraph.NewFieldSpec(extraentry.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ExtraEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, extraentry.FieldID)
		for _, f := range fields {
			if !extraentry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != extraentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(extraentry.FieldFilePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(extraentry.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(extraentry.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSizeBytes(); ok {
		_spec.SetField(extraentry.FieldFileSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSizeBytes(); ok {
		_spec.AddField(extraentry.FieldFileSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAt(); ok {
		_spec.SetField(extraentry.FieldAddedAt, field.TypeTime, value)
	}
	if _u.mutation.RecordingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   extraentry.RecordingTable,
			Columns: []string{extraentry.RecordingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recording.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecordingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   extraentry.RecordingTable,
			Columns: []string{extraentry.RecordingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recording.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ExtraEntry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{extraentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
