// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/nicolerenee/promptbook/internal/ent/historyevent"
)

// HistoryEvent is the model entity for the HistoryEvent schema.
type HistoryEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// OccurredAt holds the value of the "occurred_at" field.
	OccurredAt time.Time `json:"occurred_at,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// RecordingID holds the value of the "recording_id" field.
	RecordingID *int64 `json:"recording_id,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary string `json:"summary,omitempty"`
	// DetailsJSON holds the value of the "details_json" field.
	DetailsJSON  string `json:"details_json,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*HistoryEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case historyevent.FieldID, historyevent.FieldRecordingID:
			values[i] = new(sql.NullInt64)
		case historyevent.FieldKind, historyevent.FieldSummary, historyevent.FieldDetailsJSON:
			values[i] = new(sql.NullString)
		case historyevent.FieldOccurredAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the HistoryEvent fields.
func (_m *HistoryEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case historyevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case historyevent.FieldOccurredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field occurred_at", values[i])
			} else if value.Valid {
				_m.OccurredAt = value.Time
			}
		case historyevent.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case historyevent.FieldRecordingID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field recording_id", values[i])
			} else if value.Valid {
				_m.RecordingID = new(int64)
				*_m.RecordingID = value.Int64
			}
		case historyevent.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case historyevent.FieldDetailsJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field details_json", values[i])
			} else if value.Valid {
				_m.DetailsJSON = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the HistoryEvent.
// This includes values selected through modifiers, order, etc.
func (_m *HistoryEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this HistoryEvent.
// Note that you need to call HistoryEvent.Unwrap() before calling this method if this HistoryEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *HistoryEvent) Update() *HistoryEventUpdateOne {
	return NewHistoryEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the HistoryEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *HistoryEvent) Unwrap() *HistoryEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: HistoryEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *HistoryEvent) String() string {
	var builder strings.Builder
	builder.WriteString("HistoryEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("occurred_at=")
	builder.WriteString(_m.OccurredAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	if v := _m.RecordingID; v != nil {
		builder.WriteString("recording_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("details_json=")
	builder.WriteString(_m.DetailsJSON)
	builder.WriteByte(')')
	return builder.String()
}

// HistoryEvents is a parsable slice of HistoryEvent.
type HistoryEvents []*HistoryEvent
