// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nicolerenee/promptbook/internal/ent/historyevent"
	"github.com/nicolerenee/promptbook/internal/ent/predicate"
)

// HistoryEventUpdate is the builder for updating HistoryEvent entities.
type HistoryEventUpdate struct {
	config
	hooks    []Hook
	mutation *HistoryEventMutation
}

// Where appends a list predicates to the HistoryEventUpdate builder.
func (_u *HistoryEventUpdate) Where(ps ...predicate.HistoryEvent) *HistoryEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOccurredAt sets the "occurred_at" field.
func (_u *HistoryEventUpdate) SetOccurredAt(v time.Time) *HistoryEventUpdate {
	_u.mutation.SetOccurredAt(v)
	return _u
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_u *HistoryEventUpdate) SetNillableOccurredAt(v *time.Time) *HistoryEventUpdate {
	if v != nil {
		_u.SetOccurredAt(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *HistoryEventUpdate) SetKind(v string) *HistoryEventUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *HistoryEventUpdate) SetNillableKind(v *string) *HistoryEventUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetRecordingID sets the "recording_id" field.
func (_u *HistoryEventUpdate) SetRecordingID(v int64) *HistoryEventUpdate {
	_u.mutation.ResetRecordingID()
	_u.mutation.SetRecordingID(v)
	return _u
}

// SetNillableRecordingID sets the "recording_id" field if the given value is not nil.
func (_u *HistoryEventUpdate) SetNillableRecordingID(v *int64) *HistoryEventUpdate {
	if v != nil {
		_u.SetRecordingID(*v)
	}
	return _u
}

// AddRecordingID adds value to the "recording_id" field.
func (_u *HistoryEventUpdate) AddRecordingID(v int64) *HistoryEventUpdate {
	_u.mutation.AddRecordingID(v)
	return _u
}

// ClearRecordingID clears the value of the "recording_id" field.
func (_u *HistoryEventUpdate) ClearRecordingID() *HistoryEventUpdate {
	_u.mutation.ClearRecordingID()
	return _u
}

// SetSummary sets the "summary" field.
func (_u *HistoryEventUpdate) SetSummary(v string) *HistoryEventUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *HistoryEventUpdate) SetNillableSummary(v *string) *HistoryEventUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetDetailsJSON sets the "details_json" field.
func (_u *HistoryEventUpdate) SetDetailsJSON(v string) *HistoryEventUpdate {
	_u.mutation.SetDetailsJSON(v)
	return _u
}

// SetNillableDetailsJSON sets the "details_json" field if the given value is not nil.
func (_u *HistoryEventUpdate) SetNillableDetailsJSON(v *string) *HistoryEventUpdate {
	if v != nil {
		_u.SetDetailsJSON(*v)
	}
	return _u
}

// Mutation returns the HistoryEventMutation object of the builder.
func (_u *HistoryEventUpdate) Mutation() *HistoryEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HistoryEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HistoryEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HistoryEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HistoryEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *HistoryEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(historyevent.Table, historyevent.Columns, sqlgraph.NewFieldSpec(historyevent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OccurredAt(); ok {
		_spec.SetField(historyevent.FieldOccurredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(historyevent.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecordingID(); ok {
		_spec.SetField(historyevent.FieldRecordingID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRecordingID(); ok {
		_spec.AddField(historyevent.FieldRecordingID, field.TypeInt64, value)
	}
	if _u.mutation.RecordingIDCleared() {
		_spec.ClearField(historyevent.FieldRecordingID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(historyevent.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.DetailsJSON(); ok {
		_spec.SetField(historyevent.FieldDetailsJSON, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{historyevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HistoryEventUpdateOne is the builder for updating a single HistoryEvent entity.
type HistoryEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HistoryEventMutation
}

// SetOccurredAt sets the "occurred_at" field.
func (_u *HistoryEventUpdateOne) SetOccurredAt(v time.Time) *HistoryEventUpdateOne {
	_u.mutation.SetOccurredAt(v)
	return _u
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_u *HistoryEventUpdateOne) SetNillableOccurredAt(v *time.Time) *HistoryEventUpdateOne {
	if v != nil {
		_u.SetOccurredAt(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *HistoryEventUpdateOne) SetKind(v string) *HistoryEventUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *HistoryEventUpdateOne) SetNillableKind(v *string) *HistoryEventUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetRecordingID sets the "recording_id" field.
func (_u *HistoryEventUpdateOne) SetRecordingID(v int64) *HistoryEventUpdateOne {
	_u.mutation.ResetRecordingID()
	_u.mutation.SetRecordingID(v)
	return _u
}

// SetNillableRecordingID sets the "recording_id" field if the given value is not nil.
func (_u *HistoryEventUpdateOne) SetNillableRecordingID(v *int64) *HistoryEventUpdateOne {
	if v != nil {
		_u.SetRecordingID(*v)
	}
	return _u
}

// AddRecordingID adds value to the "recording_id" field.
func (_u *HistoryEventUpdateOne) AddRecordingID(v int64) *HistoryEventUpdateOne {
	_u.mutation.AddRecordingID(v)
	return _u
}

// ClearRecordingID clears the value of the "recording_id" field.
func (_u *HistoryEventUpdateOne) ClearRecordingID() *HistoryEventUpdateOne {
	_u.mutation.ClearRecordingID()
	return _u
}

// SetSummary sets the "summary" field.
func (_u *HistoryEventUpdateOne) SetSummary(v string) *HistoryEventUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *HistoryEventUpdateOne) SetNillableSummary(v *string) *HistoryEventUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetDetailsJSON sets the "details_json" field.
func (_u *HistoryEventUpdateOne) SetDetailsJSON(v string) *HistoryEventUpdateOne {
	_u.mutation.SetDetailsJSON(v)
	return _u
}

// SetNillableDetailsJSON sets the "details_json" field if the given value is not nil.
func (_u *HistoryEventUpdateOne) SetNillableDetailsJSON(v *string) *HistoryEventUpdateOne {
	if v != nil {
		_u.SetDetailsJSON(*v)
	}
	return _u
}

// Mutation returns the HistoryEventMutation object of the builder.
func (_u *HistoryEventUpdateOne) Mutation() *HistoryEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the HistoryEventUpdate builder.
func (_u *HistoryEventUpdateOne) Where(ps ...predicate.HistoryEvent) *HistoryEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HistoryEventUpdateOne) Select(field string, fields ...string) *HistoryEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated HistoryEvent entity.
func (_u *HistoryEventUpdateOne) Save(ctx context.Context) (*HistoryEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HistoryEventUpdateOne) SaveX(ctx context.Context) *HistoryEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HistoryEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HistoryEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *HistoryEventUpdateOne) sqlSave(ctx context.Context) (_node *HistoryEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(historyevent.Table, historyevent.Columns, sqlgraph.NewFieldSpec(historyevent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "HistoryEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, historyevent.FieldID)
		for _, f := range fields {
			if !historyevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != historyevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OccurredAt(); ok {
		_spec.SetField(historyevent.FieldOccurredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(historyevent.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecordingID(); ok {
		_spec.SetField(historyevent.FieldRecordingID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRecordingID(); ok {
		_spec.AddField(historyevent.FieldRecordingID, field.TypeInt64, value)
	}
	if _u.mutation.RecordingIDCleared() {
		_spec.ClearField(historyevent.FieldRecordingID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(historyevent.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.DetailsJSON(); ok {
		_spec.SetField(historyevent.FieldDetailsJSON, field.TypeString, value)
	}
	_node = &HistoryEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{historyevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
