// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nicolerenee/promptbook/internal/ent/jobrun"
)

// JobRunCreate is the builder for creating a JobRun entity.
type JobRunCreate struct {
	config
	mutation *JobRunMutation
	hooks    []Hook
}

// SetJobName sets the "job_name" field.
func (_c *JobRunCreate) SetJobName(v string) *JobRunCreate {
	_c.mutation.SetJobName(v)
	return _c
}

// SetQueuedAt sets the "queued_at" field.
func (_c *JobRunCreate) SetQueuedAt(v time.Time) *JobRunCreate {
	_c.mutation.SetQueuedAt(v)
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *JobRunCreate) SetStartedAt(v time.Time) *JobRunCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *JobRunCreate) SetNillableStartedAt(v *time.Time) *JobRunCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetEndedAt sets the "ended_at" field.
func (_c *JobRunCreate) SetEndedAt(v time.Time) *JobRunCreate {
	_c.mutation.SetEndedAt(v)
	return _c
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_c *JobRunCreate) SetNillableEndedAt(v *time.Time) *JobRunCreate {
	if v != nil {
		_c.SetEndedAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *JobRunCreate) SetStatus(v string) *JobRunCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetError sets the "error" field.
func (_c *JobRunCreate) SetError(v string) *JobRunCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *JobRunCreate) SetNillableError(v *string) *JobRunCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetTrigger sets the "trigger" field.
func (_c *JobRunCreate) SetTrigger(v string) *JobRunCreate {
	_c.mutation.SetTrigger(v)
	return _c
}

// SetArgs sets the "args" field.
func (_c *JobRunCreate) SetArgs(v string) *JobRunCreate {
	_c.mutation.SetArgs(v)
	return _c
}

// SetNillableArgs sets the "args" field if the given value is not nil.
func (_c *JobRunCreate) SetNillableArgs(v *string) *JobRunCreate {
	if v != nil {
		_c.SetArgs(*v)
	}
	return _c
}

// Mutation returns the JobRunMutation object of the builder.
func (_c *JobRunCreate) Mutation() *JobRunMutation {
	return _c.mutation
}

// Save creates the JobRun in the database.
func (_c *JobRunCreate) Save(ctx context.Context) (*JobRun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *JobRunCreate) SaveX(ctx context.Context) *JobRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JobRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JobRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *JobRunCreate) defaults() {
	if _, ok := _c.mutation.Error(); !ok {
		v := jobrun.DefaultError
		_c.mutation.SetError(v)
	}
	if _, ok := _c.mutation.Args(); !ok {
		v := jobrun.DefaultArgs
		_c.mutation.SetArgs(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *JobRunCreate) check() error {
	if _, ok := _c.mutation.JobName(); !ok {
		return &ValidationError{Name: "job_name", err: errors.New(`ent: missing required field "JobRun.job_name"`)}
	}
	if _, ok := _c.mutation.QueuedAt(); !ok {
		return &ValidationError{Name: "queued_at", err: errors.New(`ent: missing required field "JobRun.queued_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "JobRun.status"`)}
	}
	if _, ok := _c.mutation.Error(); !ok {
		return &ValidationError{Name: "error", err: errors.New(`ent: missing required field "JobRun.error"`)}
	}
	if _, ok := _c.mutation.Trigger(); !ok {
		return &ValidationError{Name: "trigger", err: errors.New(`ent: missing required field "JobRun.trigger"`)}
	}
	if _, ok := _c.mutation.Args(); !ok {
		return &ValidationError{Name: "args", err: errors.New(`ent: missing required field "JobRun.args"`)}
	}
	return nil
}

func (_c *JobRunCreate) sqlSave(ctx context.Context) (*JobRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *JobRunCreate) createSpec() (*JobRun, *sqlgraph.CreateSpec) {
	var (
		_node = &JobRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(jobrun.Table, sqlgraph.NewFieldSpec(jobrun.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.JobName(); ok {
		_spec.SetField(jobrun.FieldJobName, field.TypeString, value)
		_node.JobName = value
	}
	if value, ok := _c.mutation.QueuedAt(); ok {
		_spec.SetField(jobrun.FieldQueuedAt, field.TypeTime, value)
		_node.QueuedAt = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(jobrun.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.EndedAt(); ok {
		_spec.SetField(jobrun.FieldEndedAt, field.TypeTime, value)
		_node.EndedAt = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(jobrun.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(jobrun.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.Trigger(); ok {
		_spec.SetField(jobrun.FieldTrigger, field.TypeString, value)
		_node.Trigger = value
	}
	if value, ok := _c.mutation.Args(); ok {
		_spec.SetField(jobrun.FieldArgs, field.TypeString, value)
		_node.Args = value
	}
	return _node, _spec
}

// JobRunCreateBulk is the builder for creating many JobRun entities in bulk.
type JobRunCreateBulk struct {
	config
	err      error
	builders []*JobRunCreate
}

// Save creates the JobRun entities in the database.
func (_c *JobRunCreateBulk) Save(ctx context.Context) ([]*JobRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*JobRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JobRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *JobRunCreateBulk) SaveX(ctx context.Context) []*JobRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JobRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JobRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
