// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/nicolerenee/promptbook/internal/ent/jobstate"
)

// JobState is the model entity for the JobState schema.
type JobState struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// LastStartedAt holds the value of the "last_started_at" field.
	LastStartedAt *time.Time `json:"last_started_at,omitempty"`
	// LastEndedAt holds the value of the "last_ended_at" field.
	LastEndedAt *time.Time `json:"last_ended_at,omitempty"`
	// LastDurationMs holds the value of the "last_duration_ms" field.
	LastDurationMs *int `json:"last_duration_ms,omitempty"`
	// LastStatus holds the value of the "last_status" field.
	LastStatus   *string `json:"last_status,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*JobState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case jobstate.FieldLastDurationMs:
			values[i] = new(sql.NullInt64)
		case jobstate.FieldID, jobstate.FieldLastStatus:
			values[i] = new(sql.NullString)
		case jobstate.FieldLastStartedAt, jobstate.FieldLastEndedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the JobState fields.
func (_m *JobState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case jobstate.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case jobstate.FieldLastStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_started_at", values[i])
			} else if value.Valid {
				_m.LastStartedAt = new(time.Time)
				*_m.LastStartedAt = value.Time
			}
		case jobstate.FieldLastEndedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_ended_at", values[i])
			} else if value.Valid {
				_m.LastEndedAt = new(time.Time)
				*_m.LastEndedAt = value.Time
			}
		case jobstate.FieldLastDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_duration_ms", values[i])
			} else if value.Valid {
				_m.LastDurationMs = new(int)
				*_m.LastDurationMs = int(value.Int64)
			}
		case jobstate.FieldLastStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_status", values[i])
			} else if value.Valid {
				_m.LastStatus = new(string)
				*_m.LastStatus = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the JobState.
// This includes values selected through modifiers, order, etc.
func (_m *JobState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this JobState.
// Note that you need to call JobState.Unwrap() before calling this method if this JobState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *JobState) Update() *JobStateUpdateOne {
	return NewJobStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the JobState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *JobState) Unwrap() *JobState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: JobState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *JobState) String() string {
	var builder strings.Builder
	builder.WriteString("JobState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.LastStartedAt; v != nil {
		builder.WriteString("last_started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastEndedAt; v != nil {
		builder.WriteString("last_ended_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastDurationMs; v != nil {
		builder.WriteString("last_duration_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LastStatus; v != nil {
		builder.WriteString("last_status=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// JobStates is a parsable slice of JobState.
type JobStates []*JobState
