// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/nicolerenee/promptbook/internal/ent/manualimportqueue"
)

// ManualImportQueue is the model entity for the ManualImportQueue schema.
type ManualImportQueue struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// FilePath holds the value of the "file_path" field.
	FilePath string `json:"file_path,omitempty"`
	// FileSizeBytes holds the value of the "file_size_bytes" field.
	FileSizeBytes int64 `json:"file_size_bytes,omitempty"`
	// DiscoveredAt holds the value of the "discovered_at" field.
	DiscoveredAt time.Time `json:"discovered_at,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt time.Time `json:"last_seen_at,omitempty"`
	// SuggestedRecordingID holds the value of the "suggested_recording_id" field.
	SuggestedRecordingID *int64 `json:"suggested_recording_id,omitempty"`
	// SuggestedConfidence holds the value of the "suggested_confidence" field.
	SuggestedConfidence string `json:"suggested_confidence,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// ExtrasCount holds the value of the "extras_count" field.
	ExtrasCount  int `json:"extras_count,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ManualImportQueue) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case manualimportqueue.FieldID, manualimportqueue.FieldFileSizeBytes, manualimportqueue.FieldSuggestedRecordingID, manualimportqueue.FieldExtrasCount:
			values[i] = new(sql.NullInt64)
		case manualimportqueue.FieldFilePath, manualimportqueue.FieldSuggestedConfidence, manualimportqueue.FieldNotes:
			values[i] = new(sql.NullString)
		case manualimportqueue.FieldDiscoveredAt, manualimportqueue.FieldLastSeenAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ManualImportQueue fields.
func (_m *ManualImportQueue) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case manualimportqueue.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case manualimportqueue.FieldFilePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_path", values[i])
			} else if value.Valid {
				_m.FilePath = value.String
			}
		case manualimportqueue.FieldFileSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_size_bytes", values[i])
			} else if value.Valid {
				_m.FileSizeBytes = value.Int64
			}
		case manualimportqueue.FieldDiscoveredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field discovered_at", values[i])
			} else if value.Valid {
				_m.DiscoveredAt = value.Time
			}
		case manualimportqueue.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = value.Time
			}
		case manualimportqueue.FieldSuggestedRecordingID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field suggested_recording_id", values[i])
			} else if value.Valid {
				_m.SuggestedRecordingID = new(int64)
				*_m.SuggestedRecordingID = value.Int64
			}
		case manualimportqueue.FieldSuggestedConfidence:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field suggested_confidence", values[i])
			} else if value.Valid {
				_m.SuggestedConfidence = value.String
			}
		case manualimportqueue.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case manualimportqueue.FieldExtrasCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field extras_count", values[i])
			} else if value.Valid {
				_m.ExtrasCount = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ManualImportQueue.
// This includes values selected through modifiers, order, etc.
func (_m *ManualImportQueue) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ManualImportQueue.
// Note that you need to call ManualImportQueue.Unwrap() before calling this method if this ManualImportQueue
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ManualImportQueue) Update() *ManualImportQueueUpdateOne {
	return NewManualImportQueueClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ManualImportQueue entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ManualImportQueue) Unwrap() *ManualImportQueue {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ManualImportQueue is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ManualImportQueue) String() string {
	var builder strings.Builder
	builder.WriteString("ManualImportQueue(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("file_path=")
	builder.WriteString(_m.FilePath)
	builder.WriteString(", ")
	builder.WriteString("file_size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.FileSizeBytes))
	builder.WriteString(", ")
	builder.WriteString("discovered_at=")
	builder.WriteString(_m.DiscoveredAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_seen_at=")
	builder.WriteString(_m.LastSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.SuggestedRecordingID; v != nil {
		builder.WriteString("suggested_recording_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("suggested_confidence=")
	builder.WriteString(_m.SuggestedConfidence)
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("extras_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExtrasCount))
	builder.WriteByte(')')
	return builder.String()
}

// ManualImportQueues is a parsable slice of ManualImportQueue.
type ManualImportQueues []*ManualImportQueue
