// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nicolerenee/promptbook/internal/ent/performer"
	"github.com/nicolerenee/promptbook/internal/ent/predicate"
)

// PerformerUpdate is the builder for updating Performer entities.
type PerformerUpdate struct {
	config
	hooks     []Hook
	mutation  *PerformerMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the PerformerUpdate builder.
func (_u *PerformerUpdate) Where(ps ...predicate.Performer) *PerformerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *PerformerUpdate) SetName(v string) *PerformerUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PerformerUpdate) SetNillableName(v *string) *PerformerUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *PerformerUpdate) SetSlug(v string) *PerformerUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *PerformerUpdate) SetNillableSlug(v *string) *PerformerUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *PerformerUpdate) SetURL(v string) *PerformerUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *PerformerUpdate) SetNillableURL(v *string) *PerformerUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *PerformerUpdate) SetLastSeenAt(v time.Time) *PerformerUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *PerformerUpdate) SetNillableLastSeenAt(v *time.Time) *PerformerUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// Mutation returns the PerformerMutation object of the builder.
func (_u *PerformerUpdate) Mutation() *PerformerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PerformerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PerformerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PerformerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PerformerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PerformerUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PerformerUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PerformerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(performer.Table, performer.Columns, sqlgraph.NewFieldSpec(performer.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(performer.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(performer.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(performer.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(performer.FieldLastSeenAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{performer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PerformerUpdateOne is the builder for updating a single Performer entity.
type PerformerUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *PerformerMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetName sets the "name" field.
func (_u *PerformerUpdateOne) SetName(v string) *PerformerUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PerformerUpdateOne) SetNillableName(v *string) *PerformerUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *PerformerUpdateOne) SetSlug(v string) *PerformerUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *PerformerUpdateOne) SetNillableSlug(v *string) *PerformerUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *PerformerUpdateOne) SetURL(v string) *PerformerUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *PerformerUpdateOne) SetNillableURL(v *string) *PerformerUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *PerformerUpdateOne) SetLastSeenAt(v time.Time) *PerformerUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *PerformerUpdateOne) SetNillableLastSeenAt(v *time.Time) *PerformerUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// Mutation returns the PerformerMutation object of the builder.
func (_u *PerformerUpdateOne) Mutation() *PerformerMutation {
	return _u.mutation
}

// Where appends a list predicates to the PerformerUpdate builder.
func (_u *PerformerUpdateOne) Where(ps ...predicate.Performer) *PerformerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PerformerUpdateOne) Select(field string, fields ...string) *PerformerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Performer entity.
func (_u *PerformerUpdateOne) Save(ctx context.Context) (*Performer, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PerformerUpdateOne) SaveX(ctx context.Context) *Performer {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PerformerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PerformerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PerformerUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PerformerUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PerformerUpdateOne) sqlSave(ctx context.Context) (_node *Performer, err error) {
	_spec := sqlgraph.NewUpdateSpec(performer.Table, performer.Columns, sqlgraph.NewFieldSpec(performer.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Performer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, performer.FieldID)
		for _, f := range fields {
			if !performer.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != performer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(performer.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(performer.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(performer.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(performer.FieldLastSeenAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Performer{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{performer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
