// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nicolerenee/promptbook/internal/ent/profile"
)

// ProfileCreate is the builder for creating a Profile entity.
type ProfileCreate struct {
	config
	mutation *ProfileMutation
	hooks    []Hook
}

// SetEncoraID sets the "encora_id" field.
func (_c *ProfileCreate) SetEncoraID(v int64) *ProfileCreate {
	_c.mutation.SetEncoraID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ProfileCreate) SetName(v string) *ProfileCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableName(v *string) *ProfileCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetSlug sets the "slug" field.
func (_c *ProfileCreate) SetSlug(v string) *ProfileCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableSlug(v *string) *ProfileCreate {
	if v != nil {
		_c.SetSlug(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *ProfileCreate) SetUsername(v string) *ProfileCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableUsername(v *string) *ProfileCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ProfileCreate) SetStatus(v string) *ProfileCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableStatus(v *string) *ProfileCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRecordingsCount sets the "recordings_count" field.
func (_c *ProfileCreate) SetRecordingsCount(v int) *ProfileCreate {
	_c.mutation.SetRecordingsCount(v)
	return _c
}

// SetNillableRecordingsCount sets the "recordings_count" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableRecordingsCount(v *int) *ProfileCreate {
	if v != nil {
		_c.SetRecordingsCount(*v)
	}
	return _c
}

// SetWantsCount sets the "wants_count" field.
func (_c *ProfileCreate) SetWantsCount(v int) *ProfileCreate {
	_c.mutation.SetWantsCount(v)
	return _c
}

// SetNillableWantsCount sets the "wants_count" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableWantsCount(v *int) *ProfileCreate {
	if v != nil {
		_c.SetWantsCount(*v)
	}
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *ProfileCreate) SetLastSeenAt(v string) *ProfileCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableLastSeenAt(v *string) *ProfileCreate {
	if v != nil {
		_c.SetLastSeenAt(*v)
	}
	return _c
}

// SetProfileVisibility sets the "profile_visibility" field.
func (_c *ProfileCreate) SetProfileVisibility(v string) *ProfileCreate {
	_c.mutation.SetProfileVisibility(v)
	return _c
}

// SetNillableProfileVisibility sets the "profile_visibility" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableProfileVisibility(v *string) *ProfileCreate {
	if v != nil {
		_c.SetProfileVisibility(*v)
	}
	return _c
}

// SetColVisibility sets the "col_visibility" field.
func (_c *ProfileCreate) SetColVisibility(v string) *ProfileCreate {
	_c.mutation.SetColVisibility(v)
	return _c
}

// SetNillableColVisibility sets the "col_visibility" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableColVisibility(v *string) *ProfileCreate {
	if v != nil {
		_c.SetColVisibility(*v)
	}
	return _c
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_c *ProfileCreate) SetLastSyncedAt(v time.Time) *ProfileCreate {
	_c.mutation.SetLastSyncedAt(v)
	return _c
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableLastSyncedAt(v *time.Time) *ProfileCreate {
	if v != nil {
		_c.SetLastSyncedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProfileCreate) SetID(v int) *ProfileCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ProfileMutation object of the builder.
func (_c *ProfileCreate) Mutation() *ProfileMutation {
	return _c.mutation
}

// Save creates the Profile in the database.
func (_c *ProfileCreate) Save(ctx context.Context) (*Profile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProfileCreate) SaveX(ctx context.Context) *Profile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProfileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProfileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProfileCreate) defaults() {
	if _, ok := _c.mutation.Name(); !ok {
		v := profile.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Slug(); !ok {
		v := profile.DefaultSlug
		_c.mutation.SetSlug(v)
	}
	if _, ok := _c.mutation.Username(); !ok {
		v := profile.DefaultUsername
		_c.mutation.SetUsername(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := profile.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.RecordingsCount(); !ok {
		v := profile.DefaultRecordingsCount
		_c.mutation.SetRecordingsCount(v)
	}
	if _, ok := _c.mutation.WantsCount(); !ok {
		v := profile.DefaultWantsCount
		_c.mutation.SetWantsCount(v)
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		v := profile.DefaultLastSeenAt
		_c.mutation.SetLastSeenAt(v)
	}
	if _, ok := _c.mutation.ProfileVisibility(); !ok {
		v := profile.DefaultProfileVisibility
		_c.mutation.SetProfileVisibility(v)
	}
	if _, ok := _c.mutation.ColVisibility(); !ok {
		v := profile.DefaultColVisibility
		_c.mutation.SetColVisibility(v)
	}
	if _, ok := _c.mutation.LastSyncedAt(); !ok {
		v := profile.DefaultLastSyncedAt()
		_c.mutation.SetLastSyncedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProfileCreate) check() error {
	if _, ok := _c.mutation.EncoraID(); !ok {
		return &ValidationError{Name: "encora_id", err: errors.New(`ent: missing required field "Profile.encora_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Profile.name"`)}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Profile.slug"`)}
	}
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "Profile.username"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Profile.status"`)}
	}
	if _, ok := _c.mutation.RecordingsCount(); !ok {
		return &ValidationError{Name: "recordings_count", err: errors.New(`ent: missing required field "Profile.recordings_count"`)}
	}
	if _, ok := _c.mutation.WantsCount(); !ok {
		return &ValidationError{Name: "wants_count", err: errors.New(`ent: missing required field "Profile.wants_count"`)}
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "Profile.last_seen_at"`)}
	}
	if _, ok := _c.mutation.ProfileVisibility(); !ok {
		return &ValidationError{Name: "profile_visibility", err: errors.New(`ent: missing required field "Profile.profile_visibility"`)}
	}
	if _, ok := _c.mutation.ColVisibility(); !ok {
		return &ValidationError{Name: "col_visibility", err: errors.New(`ent: missing required field "Profile.col_visibility"`)}
	}
	if _, ok := _c.mutation.LastSyncedAt(); !ok {
		return &ValidationError{Name: "last_synced_at", err: errors.New(`ent: missing required field "Profile.last_synced_at"`)}
	}
	return nil
}

func (_c *ProfileCreate) sqlSave(ctx context.Context) (*Profile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProfileCreate) createSpec() (*Profile, *sqlgraph.CreateSpec) {
	var (
		_node = &Profile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(profile.Table, sqlgraph.NewFieldSpec(profile.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.EncoraID(); ok {
		_spec.SetField(profile.FieldEncoraID, field.TypeInt64, value)
		_node.EncoraID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(profile.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(profile.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(profile.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(profile.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RecordingsCount(); ok {
		_spec.SetField(profile.FieldRecordingsCount, field.TypeInt, value)
		_node.RecordingsCount = value
	}
	if value, ok := _c.mutation.WantsCount(); ok {
		_spec.SetField(profile.FieldWantsCount, field.TypeInt, value)
		_node.WantsCount = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(profile.FieldLastSeenAt, field.TypeString, value)
		_node.LastSeenAt = value
	}
	if value, ok := _c.mutation.ProfileVisibility(); ok {
		_spec.SetField(profile.FieldProfileVisibility, field.TypeString, value)
		_node.ProfileVisibility = value
	}
	if value, ok := _c.mutation.ColVisibility(); ok {
		_spec.SetField(profile.FieldColVisibility, field.TypeString, value)
		_node.ColVisibility = value
	}
	if value, ok := _c.mutation.LastSyncedAt(); ok {
		_spec.SetField(profile.FieldLastSyncedAt, field.TypeTime, value)
		_node.LastSyncedAt = value
	}
	return _node, _spec
}

// ProfileCreateBulk is the builder for creating many Profile entities in bulk.
type ProfileCreateBulk struct {
	config
	err      error
	builders []*ProfileCreate
}

// Save creates the Profile entities in the database.
func (_c *ProfileCreateBulk) Save(ctx context.Context) ([]*Profile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Profile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProfileCreateBulk) SaveX(ctx context.Context) []*Profile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProfileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
