// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/nicolerenee/promptbook/internal/ent/recordingimagechoice"
)

// RecordingImageChoice is the model entity for the RecordingImageChoice schema.
type RecordingImageChoice struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// OverlayTextOverride holds the value of the "overlay_text_override" field.
	OverlayTextOverride *string `json:"overlay_text_override,omitempty"`
	// OverlayStyleJSON holds the value of the "overlay_style_json" field.
	OverlayStyleJSON *string `json:"overlay_style_json,omitempty"`
	// OverlayDisabled holds the value of the "overlay_disabled" field.
	OverlayDisabled bool `json:"overlay_disabled,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RecordingImageChoice) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case recordingimagechoice.FieldOverlayDisabled:
			values[i] = new(sql.NullBool)
		case recordingimagechoice.FieldID:
			values[i] = new(sql.NullInt64)
		case recordingimagechoice.FieldOverlayTextOverride, recordingimagechoice.FieldOverlayStyleJSON:
			values[i] = new(sql.NullString)
		case recordingimagechoice.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RecordingImageChoice fields.
func (_m *RecordingImageChoice) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case recordingimagechoice.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case recordingimagechoice.FieldOverlayTextOverride:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field overlay_text_override", values[i])
			} else if value.Valid {
				_m.OverlayTextOverride = new(string)
				*_m.OverlayTextOverride = value.String
			}
		case recordingimagechoice.FieldOverlayStyleJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field overlay_style_json", values[i])
			} else if value.Valid {
				_m.OverlayStyleJSON = new(string)
				*_m.OverlayStyleJSON = value.String
			}
		case recordingimagechoice.FieldOverlayDisabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field overlay_disabled", values[i])
			} else if value.Valid {
				_m.OverlayDisabled = value.Bool
			}
		case recordingimagechoice.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RecordingImageChoice.
// This includes values selected through modifiers, order, etc.
func (_m *RecordingImageChoice) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RecordingImageChoice.
// Note that you need to call RecordingImageChoice.Unwrap() before calling this method if this RecordingImageChoice
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RecordingImageChoice) Update() *RecordingImageChoiceUpdateOne {
	return NewRecordingImageChoiceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RecordingImageChoice entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RecordingImageChoice) Unwrap() *RecordingImageChoice {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RecordingImageChoice is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RecordingImageChoice) String() string {
	var builder strings.Builder
	builder.WriteString("RecordingImageChoice(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.OverlayTextOverride; v != nil {
		builder.WriteString("overlay_text_override=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OverlayStyleJSON; v != nil {
		builder.WriteString("overlay_style_json=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("overlay_disabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.OverlayDisabled))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RecordingImageChoices is a parsable slice of RecordingImageChoice.
type RecordingImageChoices []*RecordingImageChoice
