// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/nicolerenee/promptbook/internal/ent/castentry"
	"github.com/nicolerenee/promptbook/internal/ent/character"
	"github.com/nicolerenee/promptbook/internal/ent/collectionentry"
	"github.com/nicolerenee/promptbook/internal/ent/historyevent"
	"github.com/nicolerenee/promptbook/internal/ent/jobrun"
	"github.com/nicolerenee/promptbook/internal/ent/manualimportqueue"
	"github.com/nicolerenee/promptbook/internal/ent/performer"
	"github.com/nicolerenee/promptbook/internal/ent/profile"
	"github.com/nicolerenee/promptbook/internal/ent/recording"
	"github.com/nicolerenee/promptbook/internal/ent/recordingimagechoice"
	"github.com/nicolerenee/promptbook/internal/ent/recordingversion"
	"github.com/nicolerenee/promptbook/internal/ent/schema"
	"github.com/nicolerenee/promptbook/internal/ent/show"
	"github.com/nicolerenee/promptbook/internal/ent/syncrun"
	"github.com/nicolerenee/promptbook/internal/ent/wantsentry"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	castentryFields := schema.CastEntry{}.Fields()
	_ = castentryFields
	// castentryDescPerformerSlug is the schema descriptor for performer_slug field.
	castentryDescPerformerSlug := castentryFields[4].Descriptor()
	// castentry.DefaultPerformerSlug holds the default value on creation for the performer_slug field.
	castentry.DefaultPerformerSlug = castentryDescPerformerSlug.Default.(string)
	// castentryDescPerformerURL is the schema descriptor for performer_url field.
	castentryDescPerformerURL := castentryFields[5].Descriptor()
	// castentry.DefaultPerformerURL holds the default value on creation for the performer_url field.
	castentry.DefaultPerformerURL = castentryDescPerformerURL.Default.(string)
	// castentryDescCharacterSlug is the schema descriptor for character_slug field.
	castentryDescCharacterSlug := castentryFields[8].Descriptor()
	// castentry.DefaultCharacterSlug holds the default value on creation for the character_slug field.
	castentry.DefaultCharacterSlug = castentryDescCharacterSlug.Default.(string)
	// castentryDescCharacterURL is the schema descriptor for character_url field.
	castentryDescCharacterURL := castentryFields[9].Descriptor()
	// castentry.DefaultCharacterURL holds the default value on creation for the character_url field.
	castentry.DefaultCharacterURL = castentryDescCharacterURL.Default.(string)
	// castentryDescCharacterOrder is the schema descriptor for character_order field.
	castentryDescCharacterOrder := castentryFields[10].Descriptor()
	// castentry.DefaultCharacterOrder holds the default value on creation for the character_order field.
	castentry.DefaultCharacterOrder = castentryDescCharacterOrder.Default.(int)
	characterFields := schema.Character{}.Fields()
	_ = characterFields
	// characterDescSlug is the schema descriptor for slug field.
	characterDescSlug := characterFields[2].Descriptor()
	// character.DefaultSlug holds the default value on creation for the slug field.
	character.DefaultSlug = characterDescSlug.Default.(string)
	// characterDescURL is the schema descriptor for url field.
	characterDescURL := characterFields[3].Descriptor()
	// character.DefaultURL holds the default value on creation for the url field.
	character.DefaultURL = characterDescURL.Default.(string)
	// characterDescLastSeenAt is the schema descriptor for last_seen_at field.
	characterDescLastSeenAt := characterFields[4].Descriptor()
	// character.DefaultLastSeenAt holds the default value on creation for the last_seen_at field.
	character.DefaultLastSeenAt = characterDescLastSeenAt.Default.(func() time.Time)
	collectionentryFields := schema.CollectionEntry{}.Fields()
	_ = collectionentryFields
	// collectionentryDescFormat is the schema descriptor for format field.
	collectionentryDescFormat := collectionentryFields[1].Descriptor()
	// collectionentry.DefaultFormat holds the default value on creation for the format field.
	collectionentry.DefaultFormat = collectionentryDescFormat.Default.(string)
	// collectionentryDescUserWatched is the schema descriptor for user_watched field.
	collectionentryDescUserWatched := collectionentryFields[3].Descriptor()
	// collectionentry.DefaultUserWatched holds the default value on creation for the user_watched field.
	collectionentry.DefaultUserWatched = collectionentryDescUserWatched.Default.(bool)
	// collectionentryDescLastSyncedAt is the schema descriptor for last_synced_at field.
	collectionentryDescLastSyncedAt := collectionentryFields[6].Descriptor()
	// collectionentry.DefaultLastSyncedAt holds the default value on creation for the last_synced_at field.
	collectionentry.DefaultLastSyncedAt = collectionentryDescLastSyncedAt.Default.(func() time.Time)
	historyeventFields := schema.HistoryEvent{}.Fields()
	_ = historyeventFields
	// historyeventDescOccurredAt is the schema descriptor for occurred_at field.
	historyeventDescOccurredAt := historyeventFields[0].Descriptor()
	// historyevent.DefaultOccurredAt holds the default value on creation for the occurred_at field.
	historyevent.DefaultOccurredAt = historyeventDescOccurredAt.Default.(func() time.Time)
	// historyeventDescSummary is the schema descriptor for summary field.
	historyeventDescSummary := historyeventFields[3].Descriptor()
	// historyevent.DefaultSummary holds the default value on creation for the summary field.
	historyevent.DefaultSummary = historyeventDescSummary.Default.(string)
	// historyeventDescDetailsJSON is the schema descriptor for details_json field.
	historyeventDescDetailsJSON := historyeventFields[4].Descriptor()
	// historyevent.DefaultDetailsJSON holds the default value on creation for the details_json field.
	historyevent.DefaultDetailsJSON = historyeventDescDetailsJSON.Default.(string)
	jobrunFields := schema.JobRun{}.Fields()
	_ = jobrunFields
	// jobrunDescError is the schema descriptor for error field.
	jobrunDescError := jobrunFields[5].Descriptor()
	// jobrun.DefaultError holds the default value on creation for the error field.
	jobrun.DefaultError = jobrunDescError.Default.(string)
	// jobrunDescArgs is the schema descriptor for args field.
	jobrunDescArgs := jobrunFields[7].Descriptor()
	// jobrun.DefaultArgs holds the default value on creation for the args field.
	jobrun.DefaultArgs = jobrunDescArgs.Default.(string)
	manualimportqueueFields := schema.ManualImportQueue{}.Fields()
	_ = manualimportqueueFields
	// manualimportqueueDescFileSizeBytes is the schema descriptor for file_size_bytes field.
	manualimportqueueDescFileSizeBytes := manualimportqueueFields[1].Descriptor()
	// manualimportqueue.DefaultFileSizeBytes holds the default value on creation for the file_size_bytes field.
	manualimportqueue.DefaultFileSizeBytes = manualimportqueueDescFileSizeBytes.Default.(int64)
	// manualimportqueueDescDiscoveredAt is the schema descriptor for discovered_at field.
	manualimportqueueDescDiscoveredAt := manualimportqueueFields[2].Descriptor()
	// manualimportqueue.DefaultDiscoveredAt holds the default value on creation for the discovered_at field.
	manualimportqueue.DefaultDiscoveredAt = manualimportqueueDescDiscoveredAt.Default.(func() time.Time)
	// manualimportqueueDescLastSeenAt is the schema descriptor for last_seen_at field.
	manualimportqueueDescLastSeenAt := manualimportqueueFields[3].Descriptor()
	// manualimportqueue.DefaultLastSeenAt holds the default value on creation for the last_seen_at field.
	manualimportqueue.DefaultLastSeenAt = manualimportqueueDescLastSeenAt.Default.(func() time.Time)
	// manualimportqueueDescSuggestedConfidence is the schema descriptor for suggested_confidence field.
	manualimportqueueDescSuggestedConfidence := manualimportqueueFields[5].Descriptor()
	// manualimportqueue.DefaultSuggestedConfidence holds the default value on creation for the suggested_confidence field.
	manualimportqueue.DefaultSuggestedConfidence = manualimportqueueDescSuggestedConfidence.Default.(string)
	// manualimportqueueDescNotes is the schema descriptor for notes field.
	manualimportqueueDescNotes := manualimportqueueFields[6].Descriptor()
	// manualimportqueue.DefaultNotes holds the default value on creation for the notes field.
	manualimportqueue.DefaultNotes = manualimportqueueDescNotes.Default.(string)
	// manualimportqueueDescExtrasCount is the schema descriptor for extras_count field.
	manualimportqueueDescExtrasCount := manualimportqueueFields[7].Descriptor()
	// manualimportqueue.DefaultExtrasCount holds the default value on creation for the extras_count field.
	manualimportqueue.DefaultExtrasCount = manualimportqueueDescExtrasCount.Default.(int)
	performerFields := schema.Performer{}.Fields()
	_ = performerFields
	// performerDescSlug is the schema descriptor for slug field.
	performerDescSlug := performerFields[2].Descriptor()
	// performer.DefaultSlug holds the default value on creation for the slug field.
	performer.DefaultSlug = performerDescSlug.Default.(string)
	// performerDescURL is the schema descriptor for url field.
	performerDescURL := performerFields[3].Descriptor()
	// performer.DefaultURL holds the default value on creation for the url field.
	performer.DefaultURL = performerDescURL.Default.(string)
	// performerDescLastSeenAt is the schema descriptor for last_seen_at field.
	performerDescLastSeenAt := performerFields[4].Descriptor()
	// performer.DefaultLastSeenAt holds the default value on creation for the last_seen_at field.
	performer.DefaultLastSeenAt = performerDescLastSeenAt.Default.(func() time.Time)
	profileFields := schema.Profile{}.Fields()
	_ = profileFields
	// profileDescName is the schema descriptor for name field.
	profileDescName := profileFields[2].Descriptor()
	// profile.DefaultName holds the default value on creation for the name field.
	profile.DefaultName = profileDescName.Default.(string)
	// profileDescSlug is the schema descriptor for slug field.
	profileDescSlug := profileFields[3].Descriptor()
	// profile.DefaultSlug holds the default value on creation for the slug field.
	profile.DefaultSlug = profileDescSlug.Default.(string)
	// profileDescUsername is the schema descriptor for username field.
	profileDescUsername := profileFields[4].Descriptor()
	// profile.DefaultUsername holds the default value on creation for the username field.
	profile.DefaultUsername = profileDescUsername.Default.(string)
	// profileDescStatus is the schema descriptor for status field.
	profileDescStatus := profileFields[5].Descriptor()
	// profile.DefaultStatus holds the default value on creation for the status field.
	profile.DefaultStatus = profileDescStatus.Default.(string)
	// profileDescRecordingsCount is the schema descriptor for recordings_count field.
	profileDescRecordingsCount := profileFields[6].Descriptor()
	// profile.DefaultRecordingsCount holds the default value on creation for the recordings_count field.
	profile.DefaultRecordingsCount = profileDescRecordingsCount.Default.(int)
	// profileDescWantsCount is the schema descriptor for wants_count field.
	profileDescWantsCount := profileFields[7].Descriptor()
	// profile.DefaultWantsCount holds the default value on creation for the wants_count field.
	profile.DefaultWantsCount = profileDescWantsCount.Default.(int)
	// profileDescLastSeenAt is the schema descriptor for last_seen_at field.
	profileDescLastSeenAt := profileFields[8].Descriptor()
	// profile.DefaultLastSeenAt holds the default value on creation for the last_seen_at field.
	profile.DefaultLastSeenAt = profileDescLastSeenAt.Default.(string)
	// profileDescProfileVisibility is the schema descriptor for profile_visibility field.
	profileDescProfileVisibility := profileFields[9].Descriptor()
	// profile.DefaultProfileVisibility holds the default value on creation for the profile_visibility field.
	profile.DefaultProfileVisibility = profileDescProfileVisibility.Default.(string)
	// profileDescColVisibility is the schema descriptor for col_visibility field.
	profileDescColVisibility := profileFields[10].Descriptor()
	// profile.DefaultColVisibility holds the default value on creation for the col_visibility field.
	profile.DefaultColVisibility = profileDescColVisibility.Default.(string)
	// profileDescLastSyncedAt is the schema descriptor for last_synced_at field.
	profileDescLastSyncedAt := profileFields[11].Descriptor()
	// profile.DefaultLastSyncedAt holds the default value on creation for the last_synced_at field.
	profile.DefaultLastSyncedAt = profileDescLastSyncedAt.Default.(func() time.Time)
	recordingFields := schema.Recording{}.Fields()
	_ = recordingFields
	// recordingDescTour is the schema descriptor for tour field.
	recordingDescTour := recordingFields[2].Descriptor()
	// recording.DefaultTour holds the default value on creation for the tour field.
	recording.DefaultTour = recordingDescTour.Default.(string)
	// recordingDescDateFull is the schema descriptor for date_full field.
	recordingDescDateFull := recordingFields[3].Descriptor()
	// recording.DefaultDateFull holds the default value on creation for the date_full field.
	recording.DefaultDateFull = recordingDescDateFull.Default.(string)
	// recordingDescDateMonthKnown is the schema descriptor for date_month_known field.
	recordingDescDateMonthKnown := recordingFields[4].Descriptor()
	// recording.DefaultDateMonthKnown holds the default value on creation for the date_month_known field.
	recording.DefaultDateMonthKnown = recordingDescDateMonthKnown.Default.(bool)
	// recordingDescDateDayKnown is the schema descriptor for date_day_known field.
	recordingDescDateDayKnown := recordingFields[5].Descriptor()
	// recording.DefaultDateDayKnown holds the default value on creation for the date_day_known field.
	recording.DefaultDateDayKnown = recordingDescDateDayKnown.Default.(bool)
	// recordingDescDateTime is the schema descriptor for date_time field.
	recordingDescDateTime := recordingFields[7].Descriptor()
	// recording.DefaultDateTime holds the default value on creation for the date_time field.
	recording.DefaultDateTime = recordingDescDateTime.Default.(string)
	// recordingDescMaster is the schema descriptor for master field.
	recordingDescMaster := recordingFields[8].Descriptor()
	// recording.DefaultMaster holds the default value on creation for the master field.
	recording.DefaultMaster = recordingDescMaster.Default.(string)
	// recordingDescNftForever is the schema descriptor for nft_forever field.
	recordingDescNftForever := recordingFields[10].Descriptor()
	// recording.DefaultNftForever holds the default value on creation for the nft_forever field.
	recording.DefaultNftForever = recordingDescNftForever.Default.(bool)
	// recordingDescNotes is the schema descriptor for notes field.
	recordingDescNotes := recordingFields[11].Descriptor()
	// recording.DefaultNotes holds the default value on creation for the notes field.
	recording.DefaultNotes = recordingDescNotes.Default.(string)
	// recordingDescVenue is the schema descriptor for venue field.
	recordingDescVenue := recordingFields[14].Descriptor()
	// recording.DefaultVenue holds the default value on creation for the venue field.
	recording.DefaultVenue = recordingDescVenue.Default.(string)
	// recordingDescCity is the schema descriptor for city field.
	recordingDescCity := recordingFields[15].Descriptor()
	// recording.DefaultCity holds the default value on creation for the city field.
	recording.DefaultCity = recordingDescCity.Default.(string)
	// recordingDescMediaType is the schema descriptor for media_type field.
	recordingDescMediaType := recordingFields[16].Descriptor()
	// recording.DefaultMediaType holds the default value on creation for the media_type field.
	recording.DefaultMediaType = recordingDescMediaType.Default.(string)
	// recordingDescRecordingType is the schema descriptor for recording_type field.
	recordingDescRecordingType := recordingFields[17].Descriptor()
	// recording.DefaultRecordingType holds the default value on creation for the recording_type field.
	recording.DefaultRecordingType = recordingDescRecordingType.Default.(string)
	// recordingDescAmountRecorded is the schema descriptor for amount_recorded field.
	recordingDescAmountRecorded := recordingFields[18].Descriptor()
	// recording.DefaultAmountRecorded holds the default value on creation for the amount_recorded field.
	recording.DefaultAmountRecorded = recordingDescAmountRecorded.Default.(string)
	// recordingDescGiftingStatus is the schema descriptor for gifting_status field.
	recordingDescGiftingStatus := recordingFields[19].Descriptor()
	// recording.DefaultGiftingStatus holds the default value on creation for the gifting_status field.
	recording.DefaultGiftingStatus = recordingDescGiftingStatus.Default.(string)
	// recordingDescLimitedStatus is the schema descriptor for limited_status field.
	recordingDescLimitedStatus := recordingFields[20].Descriptor()
	// recording.DefaultLimitedStatus holds the default value on creation for the limited_status field.
	recording.DefaultLimitedStatus = recordingDescLimitedStatus.Default.(string)
	// recordingDescIsOpening is the schema descriptor for is_opening field.
	recordingDescIsOpening := recordingFields[21].Descriptor()
	// recording.DefaultIsOpening holds the default value on creation for the is_opening field.
	recording.DefaultIsOpening = recordingDescIsOpening.Default.(bool)
	// recordingDescIsClosing is the schema descriptor for is_closing field.
	recordingDescIsClosing := recordingFields[22].Descriptor()
	// recording.DefaultIsClosing holds the default value on creation for the is_closing field.
	recording.DefaultIsClosing = recordingDescIsClosing.Default.(bool)
	// recordingDescIsPreview is the schema descriptor for is_preview field.
	recordingDescIsPreview := recordingFields[23].Descriptor()
	// recording.DefaultIsPreview holds the default value on creation for the is_preview field.
	recording.DefaultIsPreview = recordingDescIsPreview.Default.(bool)
	// recordingDescIsConcert is the schema descriptor for is_concert field.
	recordingDescIsConcert := recordingFields[24].Descriptor()
	// recording.DefaultIsConcert holds the default value on creation for the is_concert field.
	recording.DefaultIsConcert = recordingDescIsConcert.Default.(bool)
	// recordingDescIsNfs is the schema descriptor for is_nfs field.
	recordingDescIsNfs := recordingFields[25].Descriptor()
	// recording.DefaultIsNfs holds the default value on creation for the is_nfs field.
	recording.DefaultIsNfs = recordingDescIsNfs.Default.(bool)
	// recordingDescIsFavourite is the schema descriptor for is_favourite field.
	recordingDescIsFavourite := recordingFields[26].Descriptor()
	// recording.DefaultIsFavourite holds the default value on creation for the is_favourite field.
	recording.DefaultIsFavourite = recordingDescIsFavourite.Default.(bool)
	// recordingDescHasScreenshots is the schema descriptor for has_screenshots field.
	recordingDescHasScreenshots := recordingFields[27].Descriptor()
	// recording.DefaultHasScreenshots holds the default value on creation for the has_screenshots field.
	recording.DefaultHasScreenshots = recordingDescHasScreenshots.Default.(bool)
	// recordingDescHasSubtitles is the schema descriptor for has_subtitles field.
	recordingDescHasSubtitles := recordingFields[28].Descriptor()
	// recording.DefaultHasSubtitles holds the default value on creation for the has_subtitles field.
	recording.DefaultHasSubtitles = recordingDescHasSubtitles.Default.(bool)
	// recordingDescBootCampRecommended is the schema descriptor for boot_camp_recommended field.
	recordingDescBootCampRecommended := recordingFields[29].Descriptor()
	// recording.DefaultBootCampRecommended holds the default value on creation for the boot_camp_recommended field.
	recording.DefaultBootCampRecommended = recordingDescBootCampRecommended.Default.(bool)
	// recordingDescOwnersCount is the schema descriptor for owners_count field.
	recordingDescOwnersCount := recordingFields[30].Descriptor()
	// recording.DefaultOwnersCount holds the default value on creation for the owners_count field.
	recording.DefaultOwnersCount = recordingDescOwnersCount.Default.(int)
	// recordingDescWantersCount is the schema descriptor for wanters_count field.
	recordingDescWantersCount := recordingFields[31].Descriptor()
	// recording.DefaultWantersCount holds the default value on creation for the wanters_count field.
	recording.DefaultWantersCount = recordingDescWantersCount.Default.(int)
	// recordingDescLastUpdated is the schema descriptor for last_updated field.
	recordingDescLastUpdated := recordingFields[32].Descriptor()
	// recording.DefaultLastUpdated holds the default value on creation for the last_updated field.
	recording.DefaultLastUpdated = recordingDescLastUpdated.Default.(string)
	// recordingDescLastSeenAt is the schema descriptor for last_seen_at field.
	recordingDescLastSeenAt := recordingFields[34].Descriptor()
	// recording.DefaultLastSeenAt holds the default value on creation for the last_seen_at field.
	recording.DefaultLastSeenAt = recordingDescLastSeenAt.Default.(func() time.Time)
	recordingimagechoiceFields := schema.RecordingImageChoice{}.Fields()
	_ = recordingimagechoiceFields
	// recordingimagechoiceDescOverlayDisabled is the schema descriptor for overlay_disabled field.
	recordingimagechoiceDescOverlayDisabled := recordingimagechoiceFields[3].Descriptor()
	// recordingimagechoice.DefaultOverlayDisabled holds the default value on creation for the overlay_disabled field.
	recordingimagechoice.DefaultOverlayDisabled = recordingimagechoiceDescOverlayDisabled.Default.(bool)
	// recordingimagechoiceDescUpdatedAt is the schema descriptor for updated_at field.
	recordingimagechoiceDescUpdatedAt := recordingimagechoiceFields[4].Descriptor()
	// recordingimagechoice.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	recordingimagechoice.DefaultUpdatedAt = recordingimagechoiceDescUpdatedAt.Default.(func() time.Time)
	recordingversionFields := schema.RecordingVersion{}.Fields()
	_ = recordingversionFields
	// recordingversionDescFileSizeBytes is the schema descriptor for file_size_bytes field.
	recordingversionDescFileSizeBytes := recordingversionFields[3].Descriptor()
	// recordingversion.DefaultFileSizeBytes holds the default value on creation for the file_size_bytes field.
	recordingversion.DefaultFileSizeBytes = recordingversionDescFileSizeBytes.Default.(int64)
	// recordingversionDescContainer is the schema descriptor for container field.
	recordingversionDescContainer := recordingversionFields[4].Descriptor()
	// recordingversion.DefaultContainer holds the default value on creation for the container field.
	recordingversion.DefaultContainer = recordingversionDescContainer.Default.(string)
	// recordingversionDescQuality is the schema descriptor for quality field.
	recordingversionDescQuality := recordingversionFields[5].Descriptor()
	// recordingversion.DefaultQuality holds the default value on creation for the quality field.
	recordingversion.DefaultQuality = recordingversionDescQuality.Default.(string)
	// recordingversionDescVideoCodec is the schema descriptor for video_codec field.
	recordingversionDescVideoCodec := recordingversionFields[6].Descriptor()
	// recordingversion.DefaultVideoCodec holds the default value on creation for the video_codec field.
	recordingversion.DefaultVideoCodec = recordingversionDescVideoCodec.Default.(string)
	// recordingversionDescAudioCodec is the schema descriptor for audio_codec field.
	recordingversionDescAudioCodec := recordingversionFields[7].Descriptor()
	// recordingversion.DefaultAudioCodec holds the default value on creation for the audio_codec field.
	recordingversion.DefaultAudioCodec = recordingversionDescAudioCodec.Default.(string)
	// recordingversionDescFormatLabel is the schema descriptor for format_label field.
	recordingversionDescFormatLabel := recordingversionFields[8].Descriptor()
	// recordingversion.DefaultFormatLabel holds the default value on creation for the format_label field.
	recordingversion.DefaultFormatLabel = recordingversionDescFormatLabel.Default.(string)
	// recordingversionDescNotes is the schema descriptor for notes field.
	recordingversionDescNotes := recordingversionFields[9].Descriptor()
	// recordingversion.DefaultNotes holds the default value on creation for the notes field.
	recordingversion.DefaultNotes = recordingversionDescNotes.Default.(string)
	// recordingversionDescMediaInfoJSON is the schema descriptor for media_info_json field.
	recordingversionDescMediaInfoJSON := recordingversionFields[10].Descriptor()
	// recordingversion.DefaultMediaInfoJSON holds the default value on creation for the media_info_json field.
	recordingversion.DefaultMediaInfoJSON = recordingversionDescMediaInfoJSON.Default.(string)
	// recordingversionDescAddedAt is the schema descriptor for added_at field.
	recordingversionDescAddedAt := recordingversionFields[11].Descriptor()
	// recordingversion.DefaultAddedAt holds the default value on creation for the added_at field.
	recordingversion.DefaultAddedAt = recordingversionDescAddedAt.Default.(func() time.Time)
	// recordingversionDescLastSeenAt is the schema descriptor for last_seen_at field.
	recordingversionDescLastSeenAt := recordingversionFields[12].Descriptor()
	// recordingversion.DefaultLastSeenAt holds the default value on creation for the last_seen_at field.
	recordingversion.DefaultLastSeenAt = recordingversionDescLastSeenAt.Default.(func() time.Time)
	showFields := schema.Show{}.Fields()
	_ = showFields
	// showDescDescriptionHTML is the schema descriptor for description_html field.
	showDescDescriptionHTML := showFields[2].Descriptor()
	// show.DefaultDescriptionHTML holds the default value on creation for the description_html field.
	show.DefaultDescriptionHTML = showDescDescriptionHTML.Default.(string)
	// showDescLastSeenAt is the schema descriptor for last_seen_at field.
	showDescLastSeenAt := showFields[3].Descriptor()
	// show.DefaultLastSeenAt holds the default value on creation for the last_seen_at field.
	show.DefaultLastSeenAt = showDescLastSeenAt.Default.(func() time.Time)
	syncrunFields := schema.SyncRun{}.Fields()
	_ = syncrunFields
	// syncrunDescOkCount is the schema descriptor for ok_count field.
	syncrunDescOkCount := syncrunFields[4].Descriptor()
	// syncrun.DefaultOkCount holds the default value on creation for the ok_count field.
	syncrun.DefaultOkCount = syncrunDescOkCount.Default.(int)
	// syncrunDescErrorCount is the schema descriptor for error_count field.
	syncrunDescErrorCount := syncrunFields[5].Descriptor()
	// syncrun.DefaultErrorCount holds the default value on creation for the error_count field.
	syncrun.DefaultErrorCount = syncrunDescErrorCount.Default.(int)
	// syncrunDescRateLimitRemaining is the schema descriptor for rate_limit_remaining field.
	syncrunDescRateLimitRemaining := syncrunFields[6].Descriptor()
	// syncrun.DefaultRateLimitRemaining holds the default value on creation for the rate_limit_remaining field.
	syncrun.DefaultRateLimitRemaining = syncrunDescRateLimitRemaining.Default.(int)
	// syncrunDescErrorText is the schema descriptor for error_text field.
	syncrunDescErrorText := syncrunFields[7].Descriptor()
	// syncrun.DefaultErrorText holds the default value on creation for the error_text field.
	syncrun.DefaultErrorText = syncrunDescErrorText.Default.(string)
	wantsentryFields := schema.WantsEntry{}.Fields()
	_ = wantsentryFields
	// wantsentryDescLastSyncedAt is the schema descriptor for last_synced_at field.
	wantsentryDescLastSyncedAt := wantsentryFields[1].Descriptor()
	// wantsentry.DefaultLastSyncedAt holds the default value on creation for the last_synced_at field.
	wantsentry.DefaultLastSyncedAt = wantsentryDescLastSyncedAt.Default.(func() time.Time)
}
