// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nicolerenee/promptbook/internal/ent/recording"
	"github.com/nicolerenee/promptbook/internal/ent/show"
)

// ShowCreate is the builder for creating a Show entity.
type ShowCreate struct {
	config
	mutation *ShowMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *ShowCreate) SetName(v string) *ShowCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescriptionHTML sets the "description_html" field.
func (_c *ShowCreate) SetDescriptionHTML(v string) *ShowCreate {
	_c.mutation.SetDescriptionHTML(v)
	return _c
}

// SetNillableDescriptionHTML sets the "description_html" field if the given value is not nil.
func (_c *ShowCreate) SetNillableDescriptionHTML(v *string) *ShowCreate {
	if v != nil {
		_c.SetDescriptionHTML(*v)
	}
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *ShowCreate) SetLastSeenAt(v time.Time) *ShowCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_c *ShowCreate) SetNillableLastSeenAt(v *time.Time) *ShowCreate {
	if v != nil {
		_c.SetLastSeenAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ShowCreate) SetID(v int64) *ShowCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddRecordingIDs adds the "recordings" edge to the Recording entity by IDs.
func (_c *ShowCreate) AddRecordingIDs(ids ...int64) *ShowCreate {
	_c.mutation.AddRecordingIDs(ids...)
	return _c
}

// AddRecordings adds the "recordings" edges to the Recording entity.
func (_c *ShowCreate) AddRecordings(v ...*Recording) *ShowCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRecordingIDs(ids...)
}

// Mutation returns the ShowMutation object of the builder.
func (_c *ShowCreate) Mutation() *ShowMutation {
	return _c.mutation
}

// Save creates the Show in the database.
func (_c *ShowCreate) Save(ctx context.Context) (*Show, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ShowCreate) SaveX(ctx context.Context) *Show {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShowCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShowCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ShowCreate) defaults() {
	if _, ok := _c.mutation.DescriptionHTML(); !ok {
		v := show.DefaultDescriptionHTML
		_c.mutation.SetDescriptionHTML(v)
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		v := show.DefaultLastSeenAt()
		_c.mutation.SetLastSeenAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ShowCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Show.name"`)}
	}
	if _, ok := _c.mutation.DescriptionHTML(); !ok {
		return &ValidationError{Name: "description_html", err: errors.New(`ent: missing required field "Show.description_html"`)}
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "Show.last_seen_at"`)}
	}
	return nil
}

func (_c *ShowCreate) sqlSave(ctx context.Context) (*Show, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ShowCreate) createSpec() (*Show, *sqlgraph.CreateSpec) {
	var (
		_node = &Show{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(show.Table, sqlgraph.NewFieldSpec(show.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(show.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.DescriptionHTML(); ok {
		_spec.SetField(show.FieldDescriptionHTML, field.TypeString, value)
		_node.DescriptionHTML = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(show.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = value
	}
	if nodes := _c.mutation.RecordingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   show.RecordingsTable,
			Columns: []string{show.RecordingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recording.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Show.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ShowUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *ShowCreate) OnConflict(opts ...sql.ConflictOption) *ShowUpsertOne {
	_c.conflict = opts
	return &ShowUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Show.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ShowCreate) OnConflictColumns(columns ...string) *ShowUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ShowUpsertOne{
		create: _c,
	}
}

type (
	// ShowUpsertOne is the builder for "upsert"-ing
	//  one Show node.
	ShowUpsertOne struct {
		create *ShowCreate
	}

	// ShowUpsert is the "OnConflict" setter.
	ShowUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *ShowUpsert) SetName(v string) *ShowUpsert {
	u.Set(show.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ShowUpsert) UpdateName() *ShowUpsert {
	u.SetExcluded(show.FieldName)
	return u
}

// SetDescriptionHTML sets the "description_html" field.
func (u *ShowUpsert) SetDescriptionHTML(v string) *ShowUpsert {
	u.Set(show.FieldDescriptionHTML, v)
	return u
}

// UpdateDescriptionHTML sets the "description_html" field to the value that was provided on create.
func (u *ShowUpsert) UpdateDescriptionHTML() *ShowUpsert {
	u.SetExcluded(show.FieldDescriptionHTML)
	return u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *ShowUpsert) SetLastSeenAt(v time.Time) *ShowUpsert {
	u.Set(show.FieldLastSeenAt, v)
	return u
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *ShowUpsert) UpdateLastSeenAt() *ShowUpsert {
	u.SetExcluded(show.FieldLastSeenAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Show.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(show.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ShowUpsertOne) UpdateNewValues() *ShowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(show.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Show.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ShowUpsertOne) Ignore() *ShowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ShowUpsertOne) DoNothing() *ShowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ShowCreate.OnConflict
// documentation for more info.
func (u *ShowUpsertOne) Update(set func(*ShowUpsert)) *ShowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ShowUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ShowUpsertOne) SetName(v string) *ShowUpsertOne {
	return u.Update(func(s *ShowUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ShowUpsertOne) UpdateName() *ShowUpsertOne {
	return u.Update(func(s *ShowUpsert) {
		s.UpdateName()
	})
}

// SetDescriptionHTML sets the "description_html" field.
func (u *ShowUpsertOne) SetDescriptionHTML(v string) *ShowUpsertOne {
	return u.Update(func(s *ShowUpsert) {
		s.SetDescriptionHTML(v)
	})
}

// UpdateDescriptionHTML sets the "description_html" field to the value that was provided on create.
func (u *ShowUpsertOne) UpdateDescriptionHTML() *ShowUpsertOne {
	return u.Update(func(s *ShowUpsert) {
		s.UpdateDescriptionHTML()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *ShowUpsertOne) SetLastSeenAt(v time.Time) *ShowUpsertOne {
	return u.Update(func(s *ShowUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *ShowUpsertOne) UpdateLastSeenAt() *ShowUpsertOne {
	return u.Update(func(s *ShowUpsert) {
		s.UpdateLastSeenAt()
	})
}

// Exec executes the query.
func (u *ShowUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ShowCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ShowUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ShowUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ShowUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ShowCreateBulk is the builder for creating many Show entities in bulk.
type ShowCreateBulk struct {
	config
	err      error
	builders []*ShowCreate
	conflict []sql.ConflictOption
}

// Save creates the Show entities in the database.
func (_c *ShowCreateBulk) Save(ctx context.Context) ([]*Show, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Show, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShowMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ShowCreateBulk) SaveX(ctx context.Context) []*Show {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShowCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShowCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Show.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ShowUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *ShowCreateBulk) OnConflict(opts ...sql.ConflictOption) *ShowUpsertBulk {
	_c.conflict = opts
	return &ShowUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Show.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ShowCreateBulk) OnConflictColumns(columns ...string) *ShowUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ShowUpsertBulk{
		create: _c,
	}
}

// ShowUpsertBulk is the builder for "upsert"-ing
// a bulk of Show nodes.
type ShowUpsertBulk struct {
	create *ShowCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Show.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(show.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ShowUpsertBulk) UpdateNewValues() *ShowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(show.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Show.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ShowUpsertBulk) Ignore() *ShowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ShowUpsertBulk) DoNothing() *ShowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ShowCreateBulk.OnConflict
// documentation for more info.
func (u *ShowUpsertBulk) Update(set func(*ShowUpsert)) *ShowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ShowUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ShowUpsertBulk) SetName(v string) *ShowUpsertBulk {
	return u.Update(func(s *ShowUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ShowUpsertBulk) UpdateName() *ShowUpsertBulk {
	return u.Update(func(s *ShowUpsert) {
		s.UpdateName()
	})
}

// SetDescriptionHTML sets the "description_html" field.
func (u *ShowUpsertBulk) SetDescriptionHTML(v string) *ShowUpsertBulk {
	return u.Update(func(s *ShowUpsert) {
		s.SetDescriptionHTML(v)
	})
}

// UpdateDescriptionHTML sets the "description_html" field to the value that was provided on create.
func (u *ShowUpsertBulk) UpdateDescriptionHTML() *ShowUpsertBulk {
	return u.Update(func(s *ShowUpsert) {
		s.UpdateDescriptionHTML()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *ShowUpsertBulk) SetLastSeenAt(v time.Time) *ShowUpsertBulk {
	return u.Update(func(s *ShowUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *ShowUpsertBulk) UpdateLastSeenAt() *ShowUpsertBulk {
	return u.Update(func(s *ShowUpsert) {
		s.UpdateLastSeenAt()
	})
}

// Exec executes the query.
func (u *ShowUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ShowCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ShowCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ShowUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
