// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/nicolerenee/promptbook/internal/ent/syncrun"
)

// SyncRun is the model entity for the SyncRun schema.
type SyncRun struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// OkCount holds the value of the "ok_count" field.
	OkCount int `json:"ok_count,omitempty"`
	// ErrorCount holds the value of the "error_count" field.
	ErrorCount int `json:"error_count,omitempty"`
	// RateLimitRemaining holds the value of the "rate_limit_remaining" field.
	RateLimitRemaining int `json:"rate_limit_remaining,omitempty"`
	// ErrorText holds the value of the "error_text" field.
	ErrorText    string `json:"error_text,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SyncRun) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case syncrun.FieldID, syncrun.FieldOkCount, syncrun.FieldErrorCount, syncrun.FieldRateLimitRemaining:
			values[i] = new(sql.NullInt64)
		case syncrun.FieldKind, syncrun.FieldErrorText:
			values[i] = new(sql.NullString)
		case syncrun.FieldStartedAt, syncrun.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SyncRun fields.
func (_m *SyncRun) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case syncrun.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case syncrun.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case syncrun.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case syncrun.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case syncrun.FieldOkCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ok_count", values[i])
			} else if value.Valid {
				_m.OkCount = int(value.Int64)
			}
		case syncrun.FieldErrorCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field error_count", values[i])
			} else if value.Valid {
				_m.ErrorCount = int(value.Int64)
			}
		case syncrun.FieldRateLimitRemaining:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_limit_remaining", values[i])
			} else if value.Valid {
				_m.RateLimitRemaining = int(value.Int64)
			}
		case syncrun.FieldErrorText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_text", values[i])
			} else if value.Valid {
				_m.ErrorText = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SyncRun.
// This includes values selected through modifiers, order, etc.
func (_m *SyncRun) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SyncRun.
// Note that you need to call SyncRun.Unwrap() before calling this method if this SyncRun
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SyncRun) Update() *SyncRunUpdateOne {
	return NewSyncRunClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SyncRun entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SyncRun) Unwrap() *SyncRun {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SyncRun is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SyncRun) String() string {
	var builder strings.Builder
	builder.WriteString("SyncRun(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("ok_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.OkCount))
	builder.WriteString(", ")
	builder.WriteString("error_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ErrorCount))
	builder.WriteString(", ")
	builder.WriteString("rate_limit_remaining=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateLimitRemaining))
	builder.WriteString(", ")
	builder.WriteString("error_text=")
	builder.WriteString(_m.ErrorText)
	builder.WriteByte(')')
	return builder.String()
}

// SyncRuns is a parsable slice of SyncRun.
type SyncRuns []*SyncRun
