// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nicolerenee/promptbook/internal/ent/syncrun"
)

// SyncRunCreate is the builder for creating a SyncRun entity.
type SyncRunCreate struct {
	config
	mutation *SyncRunMutation
	hooks    []Hook
}

// SetKind sets the "kind" field.
func (_c *SyncRunCreate) SetKind(v string) *SyncRunCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *SyncRunCreate) SetStartedAt(v time.Time) *SyncRunCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *SyncRunCreate) SetFinishedAt(v time.Time) *SyncRunCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *SyncRunCreate) SetNillableFinishedAt(v *time.Time) *SyncRunCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetOkCount sets the "ok_count" field.
func (_c *SyncRunCreate) SetOkCount(v int) *SyncRunCreate {
	_c.mutation.SetOkCount(v)
	return _c
}

// SetNillableOkCount sets the "ok_count" field if the given value is not nil.
func (_c *SyncRunCreate) SetNillableOkCount(v *int) *SyncRunCreate {
	if v != nil {
		_c.SetOkCount(*v)
	}
	return _c
}

// SetErrorCount sets the "error_count" field.
func (_c *SyncRunCreate) SetErrorCount(v int) *SyncRunCreate {
	_c.mutation.SetErrorCount(v)
	return _c
}

// SetNillableErrorCount sets the "error_count" field if the given value is not nil.
func (_c *SyncRunCreate) SetNillableErrorCount(v *int) *SyncRunCreate {
	if v != nil {
		_c.SetErrorCount(*v)
	}
	return _c
}

// SetRateLimitRemaining sets the "rate_limit_remaining" field.
func (_c *SyncRunCreate) SetRateLimitRemaining(v int) *SyncRunCreate {
	_c.mutation.SetRateLimitRemaining(v)
	return _c
}

// SetNillableRateLimitRemaining sets the "rate_limit_remaining" field if the given value is not nil.
func (_c *SyncRunCreate) SetNillableRateLimitRemaining(v *int) *SyncRunCreate {
	if v != nil {
		_c.SetRateLimitRemaining(*v)
	}
	return _c
}

// SetErrorText sets the "error_text" field.
func (_c *SyncRunCreate) SetErrorText(v string) *SyncRunCreate {
	_c.mutation.SetErrorText(v)
	return _c
}

// SetNillableErrorText sets the "error_text" field if the given value is not nil.
func (_c *SyncRunCreate) SetNillableErrorText(v *string) *SyncRunCreate {
	if v != nil {
		_c.SetErrorText(*v)
	}
	return _c
}

// Mutation returns the SyncRunMutation object of the builder.
func (_c *SyncRunCreate) Mutation() *SyncRunMutation {
	return _c.mutation
}

// Save creates the SyncRun in the database.
func (_c *SyncRunCreate) Save(ctx context.Context) (*SyncRun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SyncRunCreate) SaveX(ctx context.Context) *SyncRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SyncRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SyncRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SyncRunCreate) defaults() {
	if _, ok := _c.mutation.OkCount(); !ok {
		v := syncrun.DefaultOkCount
		_c.mutation.SetOkCount(v)
	}
	if _, ok := _c.mutation.ErrorCount(); !ok {
		v := syncrun.DefaultErrorCount
		_c.mutation.SetErrorCount(v)
	}
	if _, ok := _c.mutation.RateLimitRemaining(); !ok {
		v := syncrun.DefaultRateLimitRemaining
		_c.mutation.SetRateLimitRemaining(v)
	}
	if _, ok := _c.mutation.ErrorText(); !ok {
		v := syncrun.DefaultErrorText
		_c.mutation.SetErrorText(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SyncRunCreate) check() error {
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "SyncRun.kind"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "SyncRun.started_at"`)}
	}
	if _, ok := _c.mutation.OkCount(); !ok {
		return &ValidationError{Name: "ok_count", err: errors.New(`ent: missing required field "SyncRun.ok_count"`)}
	}
	if _, ok := _c.mutation.ErrorCount(); !ok {
		return &ValidationError{Name: "error_count", err: errors.New(`ent: missing required field "SyncRun.error_count"`)}
	}
	if _, ok := _c.mutation.RateLimitRemaining(); !ok {
		return &ValidationError{Name: "rate_limit_remaining", err: errors.New(`ent: missing required field "SyncRun.rate_limit_remaining"`)}
	}
	if _, ok := _c.mutation.ErrorText(); !ok {
		return &ValidationError{Name: "error_text", err: errors.New(`ent: missing required field "SyncRun.error_text"`)}
	}
	return nil
}

func (_c *SyncRunCreate) sqlSave(ctx context.Context) (*SyncRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SyncRunCreate) createSpec() (*SyncRun, *sqlgraph.CreateSpec) {
	var (
		_node = &SyncRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(syncrun.Table, sqlgraph.NewFieldSpec(syncrun.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(syncrun.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(syncrun.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(syncrun.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.OkCount(); ok {
		_spec.SetField(syncrun.FieldOkCount, field.TypeInt, value)
		_node.OkCount = value
	}
	if value, ok := _c.mutation.ErrorCount(); ok {
		_spec.SetField(syncrun.FieldErrorCount, field.TypeInt, value)
		_node.ErrorCount = value
	}
	if value, ok := _c.mutation.RateLimitRemaining(); ok {
		_spec.SetField(syncrun.FieldRateLimitRemaining, field.TypeInt, value)
		_node.RateLimitRemaining = value
	}
	if value, ok := _c.mutation.ErrorText(); ok {
		_spec.SetField(syncrun.FieldErrorText, field.TypeString, value)
		_node.ErrorText = value
	}
	return _node, _spec
}

// SyncRunCreateBulk is the builder for creating many SyncRun entities in bulk.
type SyncRunCreateBulk struct {
	config
	err      error
	builders []*SyncRunCreate
}

// Save creates the SyncRun entities in the database.
func (_c *SyncRunCreateBulk) Save(ctx context.Context) ([]*SyncRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SyncRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SyncRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SyncRunCreateBulk) SaveX(ctx context.Context) []*SyncRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SyncRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SyncRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
