// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nicolerenee/promptbook/internal/ent/predicate"
	"github.com/nicolerenee/promptbook/internal/ent/wantsentry"
)

// WantsEntryDelete is the builder for deleting a WantsEntry entity.
type WantsEntryDelete struct {
	config
	hooks    []Hook
	mutation *WantsEntryMutation
}

// Where appends a list predicates to the WantsEntryDelete builder.
func (_d *WantsEntryDelete) Where(ps ...predicate.WantsEntry) *WantsEntryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *WantsEntryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WantsEntryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *WantsEntryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(wantsentry.Table, sqlgraph.NewFieldSpec(wantsentry.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// WantsEntryDeleteOne is the builder for deleting a single WantsEntry entity.
type WantsEntryDeleteOne struct {
	_d *WantsEntryDelete
}

// Where appends a list predicates to the WantsEntryDelete builder.
func (_d *WantsEntryDeleteOne) Where(ps ...predicate.WantsEntry) *WantsEntryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *WantsEntryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{wantsentry.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WantsEntryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
