// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/nicolerenee/promptbook/internal/ent/wantsentry"
)

// WantsEntry is the model entity for the WantsEntry schema.
type WantsEntry struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// LastSyncedAt holds the value of the "last_synced_at" field.
	LastSyncedAt time.Time `json:"last_synced_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WantsEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case wantsentry.FieldID:
			values[i] = new(sql.NullInt64)
		case wantsentry.FieldLastSyncedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WantsEntry fields.
func (_m *WantsEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case wantsentry.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case wantsentry.FieldLastSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_synced_at", values[i])
			} else if value.Valid {
				_m.LastSyncedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WantsEntry.
// This includes values selected through modifiers, order, etc.
func (_m *WantsEntry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this WantsEntry.
// Note that you need to call WantsEntry.Unwrap() before calling this method if this WantsEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WantsEntry) Update() *WantsEntryUpdateOne {
	return NewWantsEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WantsEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WantsEntry) Unwrap() *WantsEntry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WantsEntry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WantsEntry) String() string {
	var builder strings.Builder
	builder.WriteString("WantsEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("last_synced_at=")
	builder.WriteString(_m.LastSyncedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// WantsEntries is a parsable slice of WantsEntry.
type WantsEntries []*WantsEntry
