// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CastEntry is the predicate function for castentry builders.
type CastEntry func(*sql.Selector)

// Character is the predicate function for character builders.
type Character func(*sql.Selector)

// CollectionEntry is the predicate function for collectionentry builders.
type CollectionEntry func(*sql.Selector)

// ExtraEntry is the predicate function for extraentry builders.
type ExtraEntry func(*sql.Selector)

// HistoryEvent is the predicate function for historyevent builders.
type HistoryEvent func(*sql.Selector)

// JobRun is the predicate function for jobrun builders.
type JobRun func(*sql.Selector)

// JobState is the predicate function for jobstate builders.
type JobState func(*sql.Selector)

// ManualImportQueue is the predicate function for manualimportqueue builders.
type ManualImportQueue func(*sql.Selector)

// Performer is the predicate function for performer builders.
type Performer func(*sql.Selector)

// Profile is the predicate function for profile builders.
type Profile func(*sql.Selector)

// Recording is the predicate function for recording builders.
type Recording func(*sql.Selector)

// RecordingImageChoice is the predicate function for recordingimagechoice builders.
type RecordingImageChoice func(*sql.Selector)

// RecordingVersion is the predicate function for recordingversion builders.
type RecordingVersion func(*sql.Selector)

// Show is the predicate function for show builders.
type Show func(*sql.Selector)

// SyncRun is the predicate function for syncrun builders.
type SyncRun func(*sql.Selector)

// WantsEntry is the predicate function for wantsentry builders.
type WantsEntry func(*sql.Selector)
