// Code generated by ent, DO NOT EDIT.

package show

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the show type in the database.
	Label = "show"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "show_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescriptionHTML holds the string denoting the description_html field in the database.
	FieldDescriptionHTML = "description_html"
	// FieldLastSeenAt holds the string denoting the last_seen_at field in the database.
	FieldLastSeenAt = "last_seen_at"
	// EdgeRecordings holds the string denoting the recordings edge name in mutations.
	EdgeRecordings = "recordings"
	// RecordingFieldID holds the string denoting the ID field of the Recording.
	RecordingFieldID = "recording_id"
	// Table holds the table name of the show in the database.
	Table = "shows"
	// RecordingsTable is the table that holds the recordings relation/edge.
	RecordingsTable = "recordings"
	// RecordingsInverseTable is the table name for the Recording entity.
	// It exists in this package in order to avoid circular dependency with the "recording" package.
	RecordingsInverseTable = "recordings"
	// RecordingsColumn is the table column denoting the recordings relation/edge.
	RecordingsColumn = "show_id"
)

// Columns holds all SQL columns for show fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescriptionHTML,
	FieldLastSeenAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultDescriptionHTML holds the default value on creation for the "description_html" field.
	DefaultDescriptionHTML string
	// DefaultLastSeenAt holds the default value on creation for the "last_seen_at" field.
	DefaultLastSeenAt func() time.Time
)

// OrderOption defines the ordering options for the Show queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescriptionHTML orders the results by the description_html field.
func ByDescriptionHTML(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescriptionHTML, opts...).ToFunc()
}

// ByLastSeenAt orders the results by the last_seen_at field.
func ByLastSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeenAt, opts...).ToFunc()
}

// ByRecordingsCount orders the results by recordings count.
func ByRecordingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRecordingsStep(), opts...)
	}
}

// ByRecordings orders the results by recordings terms.
func ByRecordings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRecordingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRecordingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RecordingsInverseTable, RecordingFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RecordingsTable, RecordingsColumn),
	)
}
