// Code generated by ent, DO NOT EDIT.

package jobstate

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the jobstate type in the database.
	Label = "job_state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "job_name"
	// FieldLastStartedAt holds the string denoting the last_started_at field in the database.
	FieldLastStartedAt = "last_started_at"
	// FieldLastEndedAt holds the string denoting the last_ended_at field in the database.
	FieldLastEndedAt = "last_ended_at"
	// FieldLastDurationMs holds the string denoting the last_duration_ms field in the database.
	FieldLastDurationMs = "last_duration_ms"
	// FieldLastStatus holds the string denoting the last_status field in the database.
	FieldLastStatus = "last_status"
	// Table holds the table name of the jobstate in the database.
	Table = "job_state"
)

// Columns holds all SQL columns for jobstate fields.
var Columns = []string{
	FieldID,
	FieldLastStartedAt,
	FieldLastEndedAt,
	FieldLastDurationMs,
	FieldLastStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the JobState queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLastStartedAt orders the results by the last_started_at field.
func ByLastStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastStartedAt, opts...).ToFunc()
}

// ByLastEndedAt orders the results by the last_ended_at field.
func ByLastEndedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastEndedAt, opts...).ToFunc()
}

// ByLastDurationMs orders the results by the last_duration_ms field.
func ByLastDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastDurationMs, opts...).ToFunc()
}

// ByLastStatus orders the results by the last_status field.
func ByLastStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastStatus, opts...).ToFunc()
}
