// Code generated by ent, DO NOT EDIT.

package wantsentry

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the wantsentry type in the database.
	Label = "wants_entry"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "recording_id"
	// FieldLastSyncedAt holds the string denoting the last_synced_at field in the database.
	FieldLastSyncedAt = "last_synced_at"
	// Table holds the table name of the wantsentry in the database.
	Table = "wants"
)

// Columns holds all SQL columns for wantsentry fields.
var Columns = []string{
	FieldID,
	FieldLastSyncedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLastSyncedAt holds the default value on creation for the "last_synced_at" field.
	DefaultLastSyncedAt func() time.Time
)

// OrderOption defines the ordering options for the WantsEntry queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLastSyncedAt orders the results by the last_synced_at field.
func ByLastSyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncedAt, opts...).ToFunc()
}
