// Code generated by ent, DO NOT EDIT.

package extraentry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the extraentry type in the database.
	Label = "extra_entry"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRecordingID holds the string denoting the recording_id field in the database.
	FieldRecordingID = "recording_id"
	// FieldFilePath holds the string denoting the file_path field in the database.
	FieldFilePath = "file_path"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldLabel holds the string denoting the label field in the database.
	FieldLabel = "label"
	// FieldFileSizeBytes holds the string denoting the file_size_bytes field in the database.
	FieldFileSizeBytes = "file_size_bytes"
	// FieldAddedAt holds the string denoting the added_at field in the database.
	FieldAddedAt = "added_at"
	// EdgeRecording holds the string denoting the recording edge name in mutations.
	EdgeRecording = "recording"
	// RecordingFieldID holds the string denoting the ID field of the Recording.
	RecordingFieldID = "recording_id"
	// Table holds the table name of the extraentry in the database.
	Table = "recording_extras"
	// RecordingTable is the table that holds the recording relation/edge.
	RecordingTable = "recording_extras"
	// RecordingInverseTable is the table name for the Recording entity.
	// It exists in this package in order to avoid circular dependency with the "recording" package.
	RecordingInverseTable = "recordings"
	// RecordingColumn is the table column denoting the recording relation/edge.
	RecordingColumn = "recording_id"
)

// Columns holds all SQL columns for extraentry fields.
var Columns = []string{
	FieldID,
	FieldRecordingID,
	FieldFilePath,
	FieldKind,
	FieldLabel,
	FieldFileSizeBytes,
	FieldAddedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLabel holds the default value on creation for the "label" field.
	DefaultLabel string
	// DefaultFileSizeBytes holds the default value on creation for the "file_size_bytes" field.
	DefaultFileSizeBytes int64
	// DefaultAddedAt holds the default value on creation for the "added_at" field.
	DefaultAddedAt func() time.Time
)

// OrderOption defines the ordering options for the ExtraEntry queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRecordingID orders the results by the recording_id field.
func ByRecordingID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordingID, opts...).ToFunc()
}

// ByFilePath orders the results by the file_path field.
func ByFilePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilePath, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByLabel orders the results by the label field.
func ByLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLabel, opts...).ToFunc()
}

// ByFileSizeBytes orders the results by the file_size_bytes field.
func ByFileSizeBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileSizeBytes, opts...).ToFunc()
}

// ByAddedAt orders the results by the added_at field.
func ByAddedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddedAt, opts...).ToFunc()
}

// ByRecordingField orders the results by recording field.
func ByRecordingField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRecordingStep(), sql.OrderByField(field, opts...))
	}
}
func newRecordingStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RecordingInverseTable, RecordingFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RecordingTable, RecordingColumn),
	)
}
