// Code generated by ent, DO NOT EDIT.

package historyevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the historyevent type in the database.
	Label = "history_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOccurredAt holds the string denoting the occurred_at field in the database.
	FieldOccurredAt = "occurred_at"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldRecordingID holds the string denoting the recording_id field in the database.
	FieldRecordingID = "recording_id"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldDetailsJSON holds the string denoting the details_json field in the database.
	FieldDetailsJSON = "details_json"
	// Table holds the table name of the historyevent in the database.
	Table = "history"
)

// Columns holds all SQL columns for historyevent fields.
var Columns = []string{
	FieldID,
	FieldOccurredAt,
	FieldKind,
	FieldRecordingID,
	FieldSummary,
	FieldDetailsJSON,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultOccurredAt holds the default value on creation for the "occurred_at" field.
	DefaultOccurredAt func() time.Time
	// DefaultSummary holds the default value on creation for the "summary" field.
	DefaultSummary string
	// DefaultDetailsJSON holds the default value on creation for the "details_json" field.
	DefaultDetailsJSON string
)

// OrderOption defines the ordering options for the HistoryEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOccurredAt orders the results by the occurred_at field.
func ByOccurredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOccurredAt, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByRecordingID orders the results by the recording_id field.
func ByRecordingID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordingID, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// ByDetailsJSON orders the results by the details_json field.
func ByDetailsJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDetailsJSON, opts...).ToFunc()
}
