// Code generated by ent, DO NOT EDIT.

package historyevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/nicolerenee/promptbook/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldLTE(FieldID, id))
}

// OccurredAt applies equality check predicate on the "occurred_at" field. It's identical to OccurredAtEQ.
func OccurredAt(v time.Time) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldEQ(FieldOccurredAt, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldEQ(FieldKind, v))
}

// RecordingID applies equality check predicate on the "recording_id" field. It's identical to RecordingIDEQ.
func RecordingID(v int64) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldEQ(FieldRecordingID, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldEQ(FieldSummary, v))
}

// DetailsJSON applies equality check predicate on the "details_json" field. It's identical to DetailsJSONEQ.
func DetailsJSON(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldEQ(FieldDetailsJSON, v))
}

// OccurredAtEQ applies the EQ predicate on the "occurred_at" field.
func OccurredAtEQ(v time.Time) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldEQ(FieldOccurredAt, v))
}

// OccurredAtNEQ applies the NEQ predicate on the "occurred_at" field.
func OccurredAtNEQ(v time.Time) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldNEQ(FieldOccurredAt, v))
}

// OccurredAtIn applies the In predicate on the "occurred_at" field.
func OccurredAtIn(vs ...time.Time) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldIn(FieldOccurredAt, vs...))
}

// OccurredAtNotIn applies the NotIn predicate on the "occurred_at" field.
func OccurredAtNotIn(vs ...time.Time) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldNotIn(FieldOccurredAt, vs...))
}

// OccurredAtGT applies the GT predicate on the "occurred_at" field.
func OccurredAtGT(v time.Time) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldGT(FieldOccurredAt, v))
}

// OccurredAtGTE applies the GTE predicate on the "occurred_at" field.
func OccurredAtGTE(v time.Time) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldGTE(FieldOccurredAt, v))
}

// OccurredAtLT applies the LT predicate on the "occurred_at" field.
func OccurredAtLT(v time.Time) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldLT(FieldOccurredAt, v))
}

// OccurredAtLTE applies the LTE predicate on the "occurred_at" field.
func OccurredAtLTE(v time.Time) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldLTE(FieldOccurredAt, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldContainsFold(FieldKind, v))
}

// RecordingIDEQ applies the EQ predicate on the "recording_id" field.
func RecordingIDEQ(v int64) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldEQ(FieldRecordingID, v))
}

// RecordingIDNEQ applies the NEQ predicate on the "recording_id" field.
func RecordingIDNEQ(v int64) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldNEQ(FieldRecordingID, v))
}

// RecordingIDIn applies the In predicate on the "recording_id" field.
func RecordingIDIn(vs ...int64) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldIn(FieldRecordingID, vs...))
}

// RecordingIDNotIn applies the NotIn predicate on the "recording_id" field.
func RecordingIDNotIn(vs ...int64) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldNotIn(FieldRecordingID, vs...))
}

// RecordingIDGT applies the GT predicate on the "recording_id" field.
func RecordingIDGT(v int64) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldGT(FieldRecordingID, v))
}

// RecordingIDGTE applies the GTE predicate on the "recording_id" field.
func RecordingIDGTE(v int64) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldGTE(FieldRecordingID, v))
}

// RecordingIDLT applies the LT predicate on the "recording_id" field.
func RecordingIDLT(v int64) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldLT(FieldRecordingID, v))
}

// RecordingIDLTE applies the LTE predicate on the "recording_id" field.
func RecordingIDLTE(v int64) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldLTE(FieldRecordingID, v))
}

// RecordingIDIsNil applies the IsNil predicate on the "recording_id" field.
func RecordingIDIsNil() predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldIsNull(FieldRecordingID))
}

// RecordingIDNotNil applies the NotNil predicate on the "recording_id" field.
func RecordingIDNotNil() predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldNotNull(FieldRecordingID))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldContainsFold(FieldSummary, v))
}

// DetailsJSONEQ applies the EQ predicate on the "details_json" field.
func DetailsJSONEQ(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldEQ(FieldDetailsJSON, v))
}

// DetailsJSONNEQ applies the NEQ predicate on the "details_json" field.
func DetailsJSONNEQ(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldNEQ(FieldDetailsJSON, v))
}

// DetailsJSONIn applies the In predicate on the "details_json" field.
func DetailsJSONIn(vs ...string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldIn(FieldDetailsJSON, vs...))
}

// DetailsJSONNotIn applies the NotIn predicate on the "details_json" field.
func DetailsJSONNotIn(vs ...string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldNotIn(FieldDetailsJSON, vs...))
}

// DetailsJSONGT applies the GT predicate on the "details_json" field.
func DetailsJSONGT(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldGT(FieldDetailsJSON, v))
}

// DetailsJSONGTE applies the GTE predicate on the "details_json" field.
func DetailsJSONGTE(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldGTE(FieldDetailsJSON, v))
}

// DetailsJSONLT applies the LT predicate on the "details_json" field.
func DetailsJSONLT(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldLT(FieldDetailsJSON, v))
}

// DetailsJSONLTE applies the LTE predicate on the "details_json" field.
func DetailsJSONLTE(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldLTE(FieldDetailsJSON, v))
}

// DetailsJSONContains applies the Contains predicate on the "details_json" field.
func DetailsJSONContains(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldContains(FieldDetailsJSON, v))
}

// DetailsJSONHasPrefix applies the HasPrefix predicate on the "details_json" field.
func DetailsJSONHasPrefix(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldHasPrefix(FieldDetailsJSON, v))
}

// DetailsJSONHasSuffix applies the HasSuffix predicate on the "details_json" field.
func DetailsJSONHasSuffix(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldHasSuffix(FieldDetailsJSON, v))
}

// DetailsJSONEqualFold applies the EqualFold predicate on the "details_json" field.
func DetailsJSONEqualFold(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldEqualFold(FieldDetailsJSON, v))
}

// DetailsJSONContainsFold applies the ContainsFold predicate on the "details_json" field.
func DetailsJSONContainsFold(v string) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.FieldContainsFold(FieldDetailsJSON, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.HistoryEvent) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.HistoryEvent) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.HistoryEvent) predicate.HistoryEvent {
	return predicate.HistoryEvent(sql.NotPredicates(p))
}
